### ISSUE TITLE
Looking for maintainers!

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mst-gql#1]
I think this project is very promising. However, since I am currently not running any projects that use mobx-state-tree and GraphQL in real life. And beyond that, I'm currently running to many OSS projects already :)

So, consider becoming a maintainer of this project if you want to see this project to be continued!

**Comment by mweststrate** [comment]
Invited so far @elie222 @dpnolte, welcome aboard!

**Comment by dpnolte** [comment]
Thanks! My availability is shifting depending on whether I've an assignment, but always happy to help. And more importantly: when is the first Friday afternoon drinks?

**Comment by chrisdrackett** [comment]
@mweststrate can we add @zenflow to the project?

**Comment by zenflow** [comment]
Thanks @chrisdrackett! I am definitely interested in helping to maintain this project and develop it to it's full potential!

**Comment by mweststrate** [comment]
added @chrisdrackett @zenflow !

**Comment by RXminuS** [comment]
We are using this in production now so happy to invest more team resources in it :-)

**Comment by mweststrate** [comment]
@RXminuS awesome! I'll send an invite. @chrisdrackett is probably the best person to coordinate with :)

**Comment by chrisdrackett** [comment]
fyi we now have an early spectrum chat at https://spectrum.chat/mst-gql/ I'm not sure the best way to get a list of the current collaborators, but if you are one (@elie222, @mweststrate, @dpnolte) and want I can add you to the private `#Collaborators` channel so we can discuss releases timing, process, etc.

**Comment by mattiasewers** [comment]
@chrisdrackett I'd like to be added!

**Comment by chrisdrackett** [comment]
@mweststrate can we add @godness84 to the project?

**Comment by mweststrate** [comment]
Sure! But that handle doesn't seem to exist :)

**Comment by godness84** [comment]
Happy to be on board! :tada:

**Comment by rdewolff** [comment]
> We are using this in production now so happy to invest more team resources in it :-)

How is it running in production ? How much are you testing this ?

**Comment by fullofcaffeine** [comment]
Can we close this? I think there are already enough maintainers?

**Comment by fullofcaffeine** [comment]
@chrisdrackett Nice :) ... there's still the warning in the README though? If you guys give the greenlight, I can take care of this chore and submit a PR.

**Comment by chrisdrackett** [comment]
@mweststrate can we add @special-character to this repo please?

**Comment by mweststrate** [comment]
Done!
