### ISSUE TITLE
Add error when trying to use reserved names for models

### ISSUE THREAD

**Issue by RXminuS** [mobxjs/mst-gql#108]
Hey,

We had a GraphQL model called Subscription (based on Stripe) that mst-gql (I still maintain mstQL (Mysitical) #7 is better :-P ) didn't generate any models for. I think it's because of a possible naming conflict with GraphQL subscriptions but it would at least be good to show an error.

This is probably something I can fix myself, just not sure if I'll have the time this week so thought I'd at least start the issue.

**Comment by Matth10** [comment]
I think this issue can be closed.
