### ISSUE TITLE
remove promise.finally to fix react-native

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mst-gql#118]
promise.finally can cause issues in some versions of react-native. I see we recently added a new instance of it here:

https://github.com/mobxjs/mst-gql/blob/5479a544b7c2e9dc2e0e83b2ebad393839318947/src/MSTGQLStore.ts#L144

I'm not super strong in how promises work atm, so I'm wondering if someone else could take a look.

/cc @zenflow

**Comment by RXminuS** [comment]
Maybe we could rewrite to async/await instead? Make the code a lot clearer and since we compile it down anyways it shouldn't be a problem right?

**Comment by RXminuS** [comment]
What is the specific issue in React Native? Last I used Promise.finally it didn't exist in ES6 yet so thought we were using something like Bluebird, but seems that it's part of the standard Promise now.

Only issues I could find seem to indicate it is fixed now:
https://github.com/facebook/react-native/issues/19490

**Comment by chrisdrackett** [comment]
it is fixed now, but a lot of people (including everyone using expo—me—for example) are not yet on that version of RN :)

**Comment by chrisdrackett** [comment]
for now I can use `0.4.1` without much issue, so maybe this is a non-issue on some level. That being said, I'd love to reduce incompatibility wherever possible.

**Comment by RXminuS** [comment]
Ok, I understand. On the flip side it feels a bit weird to write fixes for correct code just to accommodate issues in other libraries. You'd end up with something like below if you still want to make a PR But imho I don't think it's something that should be fixed here.

```js
let handled = false
promise.then(()=> {
   handled = true;
   finally();
}.catch(() => {
  if(!handled){
     finally();
  }
})
```

**Comment by chrisdrackett** [comment]
no, I agree, it just means that I'm going to be stuck in the past on `mst-gql` for a while while waiting for expo to upgrade react native :)

**Comment by RXminuS** [comment]
In that case, I would just fork it for yourself, make the change above and setup [dependabot](https://dependabot.com/) to automatically merge in changes upstream.

**Comment by zenflow** [comment]
Actually the code to avoid using `finally` is not that complicated:

Replace this

https://github.com/mobxjs/mst-gql/blob/5479a544b7c2e9dc2e0e83b2ebad393839318947/src/MSTGQLStore.ts#L144-L146

with this:

```js
const onSettled = () => self.__promises.delete(queryKey)
promise.then(onSettled, onSettled)
```

Though I agree that we generally shouldn't use workarounds here to accommodate issues in other libraries, I don't see any problem with it in this case as a courtesy to @chrisdrackett since it's so simple. @RXminuS are you cool with that?

**Comment by RXminuS** [comment]
I'm not really anyone to set a direction here but what we've seen when making fixes like this is that they suddenly at some point get undone in a PR by someone who cleans up the code for an idiomatic pattern. And then suddenly the code breaks again for people that relied on it. And also that this fix won't propagate to other / future uses of `finally` either.

I know it's maybe a bit Googley "we fix the root problem not the effect" but If `finally` is in fact a problem that we want to account for then I think we need to adopt it on a larger scope  then just an incremental fix change, even though it would be easy to do.

**Comment by RXminuS** [comment]
Again, I'm not the one to make a decision on that but that's been our experience in the past.

**Comment by chrisdrackett** [comment]
This is a hard one as `Promise.prototype.finally` has fairly wide browser support (~88%). As noted the react-native bug has been fixed and in a couple months when expo upgrades it won't be a problem there either. My gut is to just use the simple fix for now as at the end up the day it results in more compatibility without any real downsides. If another `finally` slips in by accident in a couple months expo probably would have already updated and if no users have a problem it will probably be fine? ¯\_(ツ)_/¯

**Comment by zenflow** [comment]
Yeah, I feel like by the time another `Promise.prototype.finally` slips into the code base, expo will probably be upgraded and that bug won't be an issue anymore. And if not, there's no harm done; we just temporarily lose RN support again and are back to where we are now. I think that still helps things quite a bit. There's no need for a long-term solution for a short-term problem.
