### ISSUE TITLE
add pre-update and post-update ability to optimistic updates

### ISSUE THREAD

**Issue by RXminuS** [mobxjs/mst-gql#121]
Currently, Optimistic Updates are only rolled back in the case of an error. However, sometimes we want to insert a model optimistically with a temporary id and then once the resolver returns replace it with the actual object.

Projects like Meteor allowed for a much broader set of Optimistic Updates because it would essentially be like eventual consistency between the server and client. But maybe we can achieve some of that effect by **always** rolling back the optimistic update before we return the result?

**Comment by chrisdrackett** [comment]
there is discussion on this here: https://github.com/mobxjs/mst-gql/issues/61

**Comment by RXminuS** [comment]
Ah sorry missed that. Why was the issue closed? Our inserting of a temporary object wasn't actually that involved so hadn't thought about the edge case yet of actually having to update the optimistic item you inserted.

Would it maybe make sense to make the optimistic function call two-fold? One that's called before a resolve, one that is called after the resolve but before the merge? Like a `beforeSubmit` and a `beforePatch` hook? That way you could update the "optimistic update" with details returned from the result?

**Comment by chrisdrackett** [comment]
I like the idea of having a pre and post update hooks, that would be a really nice feature IMO.

**Comment by chrisdrackett** [comment]
Thinking about this more I think this is actually already covered because you can take the `pre` action as part of the optimistic update and any post action when the query comes back (loading becomes `false` for example)
