### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by RXminuS** [mobxjs/mst-gql#123]
We're getting an unhandled promise rejection whenever our graphql server returns an error (so 200 response code but with an error object inside).

The problem seems to come somewhere from around how the graphQLClient.request is async and can call

` throw new ClientError({ ...errorResult, status: response.status }, { query });`

and that this is called in the `MSTGQLStore.query` method and saved into the promise variable. At some point, we must miss to properly handle the catch or something but I've been digging around the last few hours and wasn't able to find it.

@chrisdrackett I believe it's somewhere around where you made the change from `finally --> catch(resolve, reject)` but not quite sure. To recreate the issue just make the graphQLClient throw a client error and check your console logs.

**Comment by chrisdrackett** [comment]
if there is an error on the server shouldn't it be returning a 500?

**Comment by RXminuS** [comment]
No that's the weird thing. I handle the error in a try-catch block but you still get this message.

**Comment by chrisdrackett** [comment]
I think we're going to need more info to move forward on this. Can you post a minimal test case? logs?

I'm also still confused about a GraphQL server sending an error back within a 200 status code.

**Comment by RXminuS** [comment]
https://www.apollographql.com/docs/apollo-server/data/errors/ is how errors are returned with a 200 status code. I'll see if I can make a small repo.

**Comment by odjhey** [comment]
This might be related, a fix for the unhandled rejection. During offline mode, requests usually yields Network Request errors, i just added a catch block.

https://github.com/odjhey/mst-gql/commit/68eb6bd4dcdfbc6b265de29b6e757b2eecec6cba

**Comment by odjhey** [comment]
@giaset , thanks! I suggest you raise a new issue/PR with the fix, seeing as this issue is a little old and may be outdated, im not on top of things currently so can't say for sure.
