### ISSUE TITLE
GraphQL over websocket?

### ISSUE THREAD

**Issue by fullofcaffeine** [mobxjs/mst-gql#131]
_Apologies if this seems a bit OT, it might be, but I think it's still relevant since it's related to the underlying GraphQL implementation of `mst-gql`._

I know subscriptions are run through websockets already, and `mst-gql` already supports them transparently, but I was wondering if it currently somehow supports (through the graphql client library it uses) running graphql completely (which would include mutations and queries, besides subscriptions) over a websocket connection? 

This could be useful for hardcore real-time apps. It seems Apollo already supports that in its client library: https://github.com/apollographql/subscriptions-transport-ws allows for. Also, it could provide for a complete (and argably simpler) graphql-based alternative to [featherjs](https://feathersjs.com/) (which is also quite nice).

Thanks in advance!

**Comment by odjhey** [comment]
Hello, not really sure i understand what you mean, but looking at source, you can achieve this by providing only wsClient (no httpClient).

https://github.com/mobxjs/mst-gql/blob/6337b0d5513804d7868f9552bdb296e8ea121c50/src/MSTGQLStore.ts#L60

**Comment by fullofcaffeine** [comment]
Hi @odjhey,

> Hello, not really sure i understand what you mean,
I was just curious, it's not meant to be an issue report.

Thanks for pointing me out to the right direction. Nice to know `mst-gql` supports switching fully to the websockets transports transparently!

Closing this.
