### ISSUE TITLE
How to properly extend a model?

### ISSUE THREAD

**Issue by fullofcaffeine** [mobxjs/mst-gql#133]
I'm working on implementing user auth in my app and I'd like to use `mst` to trigger the signup mutation + keep the and control the whole signin flow in the user model. I've found the following example that I'm basing my solution off:

https://spectrum.chat/mobx-state-tree/general/example-user-store-model~b0acbfee-2113-4951-82a2-0cc0721c8893

I have a User model that was generated by `mst-gql` and I'd like to modify it to add additional observable writeable properties to it (based off the example above):

```typescript
export const UserModel = UserModelBase
  .model({
    username: types.string,
    state: types.enumeration('State', [LOGGED_IN, LOGGED_OUT, PENDING_LOGIN]),
    loginFailed: false,
  })
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
  .views(self => ({
    get isLoggedIn() {
      return self.state === LOGGED_IN;
    },
    get isLoggedOut() {
      return self.state === LOGGED_OUT;
    },
    get isPendingLogin() {
      return self.state === PENDING_LOGIN;
    },
    get loginFailed() {
      return self.loginFailed;
    },
  }))
  .actions(self => ({
    login: flow(function* login(creds) {
      self.state = PENDING_LOGIN;
      try {
        self.username = yield self.store.mutateSignin(creds) // *[0] See comment at the bottom of the issue
        self.state = LOGGED_IN;
      } catch (err) {
        self.state = LOGGED_OUT;
        self.loginFailed = true;
      }
    }),
 }));
```

However, I have no idea how to do that. I've tried `.model`, but that method is not available for the `UserModelBase`. That's how it's shown in the snippet above (won't compile, of course).

I also tried `props()`, and it seems to work, but then TS complains that `self.loginFailed` is read-only.

I'm a bit lost on how to properly extend it. Or maybe I should consider another approach? Any insights appreciated! :)

---

*[0] _As a related note to https://github.com/mobxjs/mst-gql/issues/132, here the TS completion works and I'm able to get the completion hint for all query and mutation methods available + completion hints for the params._

**Comment by odjhey** [comment]
Hello, props can work.

And fix the typing to `types.boolean`

> ```ts
>     loginFailed: false,
> ```

**Comment by fullofcaffeine** [comment]
@odjhey Hi! Thanks for taking the time to look into it and reply! I'll try with props again. Not sure why I got the "read-only" error from TS, but probably did something wrong. Will come back to this issue tomorrow after I try it out.

**Comment by godness84** [comment]
@fullofcaffeine `loginFailed` is declared twice, as a prop (`loginFailed: false`) and as a computed value (`get loginFailed(){ ... }`). Since a computed value is readonly, typescript is complaining. Remove the computed value `get isLoginFailed(){ ... }` and you're done :)

**Comment by chrisdrackett** [comment]
also `loginFailed: false` is fine, you could also use `types.boolean` but that can be inferred from the default value without issue.

**Comment by fullofcaffeine** [comment]
Thanks a lot for all the help! 

I now see it was actually described in the README. What confused me was the error TS gave, but should have looked further into it, since it's a simple mistake. 

Apologies for the n00b questions, and thanks a lot for mst-gql, I'm really enjoying it!
