### ISSUE TITLE
Model cannot find the store/parent at depth 2

### ISSUE THREAD

**Issue by fullofcaffeine** [mobxjs/mst-gql#135]
Hi,

I initially created an issue at the `mobx-state-tree` repo, but found out it was related to `mst-gql` insted.

There's a thorough explanation here: https://github.com/mobxjs/mobx-state-tree/issues/1408.

**TL;DR**: I wasn't able to get to the root store from within a model in order to call the mst-gql-generated GraphQL query/mutation functions. I was getting a `Uncaught Error: [mobx-state-tree] Failed to find the parent of User@/me(id: Guest) at depth 2` error. 

After some digging, I fixed it by replacing the `getParent(self, 2)` call [here](https://github.com/mobxjs/mst-gql/blob/master/src/MSTGQLObject.ts#L43) by `getRoot(self)`.

I don't know if this is a bug or if it's related to something I did wrong. If it's confirmed to be a bug, I'll gladly prepare a PR, if not, any insights would be greatly appreciated!

**Comment by fullofcaffeine** [comment]
Does anyone know if there's any specific reason it's using getParent(self, 2), which seems to be relative and prone to errors if the depth changes, to getRoot, which seems to be absolute and safer to access from anywhere?

**Comment by chrisdrackett** [comment]
not sure, @mweststrate can you comment?

**Comment by mweststrate** [comment]
getRoot is prone to the opposite problem; additional wrapping of your store in other stores. Since all models that use parent and are code generated, should live at level 2, I think that should be safer?

Probably we should use `getParentByType`, which is not sensitive to depth changes.

**Comment by fullofcaffeine** [comment]
@mweststrate What would you recommend me to do in my case? The model in question lives at a `me` prop in the RootStore.

**Comment by fullofcaffeine** [comment]
And adding to that: it's created using `types.optional(types.lazy(() => UserModel), () => ({id: 'Guest'}))`.

**Comment by fullofcaffeine** [comment]
@mweststrate `getParentByType`, is that how the method is named? I couldn't find it in `mobx-state-tree`'s README. Did you mean [this one ](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/API/README.md#getparentoftype)instead?

**Comment by fullofcaffeine** [comment]
```typescript
export const RootStore = RootStoreBase
  .props({
    me: types.optional(UserModel, () => UserModel.create({id: 'Guest'})),
  });
```

**Comment by mweststrate** [comment]
Yes that was the func I was referring to.

There is nothing really special about depth; depth just refers to the
amount of nodes between two things. Just keep in mind that maps and arrays
count as independent nodes. It is very similar to a folder / file
structure. So '2' means '2 folders up'

By the way, if this is an mst-gql project, and UserModel is a generated
model, the store should already have a place to store UserModels (users
prop probably). So in that case I'd expect `me` to be a reference to a user
from the user collection, rather than something that lives in a property
that only has meaning client side. Now I can imagine that "Guest" does not
live on your backend, but in that case I'd expect guest to be modeled as a
separate type, since a guest is not a real user? So that would result into
something like `me: types.optional(types.union(types.reference(UserModel),
GuestModel), () => ({ some stuff for guest })`.

**Comment by fullofcaffeine** [comment]
> By the way, if this is an mst-gql project, and UserModel is a generated
> model, the store should already have a place to store UserModels (users
> prop probably). So in that case I'd expect `me` to be a reference to a user
> from the user collection, rather than something that lives in a property
> that only has meaning client side. Now I can imagine that "Guest" does not
> live on your backend, but in that case I'd expect guest to be modeled as a
> separate type, since a guest is not a real user? So that would result into
> something like `me: types.optional(types.union(types.reference(UserModel),
> GuestModel), () => ({ some stuff for guest })`.

Thanks for the insights. That makes sense. 

> Now I can imagine that "Guest" does not
> live on your backend, but in that case I'd expect guest to be modeled as a
> separate type, since a guest is not a real user? 

Not a user on the backend, yes, but some features of the site can be used by a Guest (which is basically a signed-out user).

How would I go about creating the instance of that user though in the collection provided by `mst-gql`?

**Comment by fullofcaffeine** [comment]
It seems to me that's it's not straightforward (or desirable?) to mix MST models with plain mobx-state-tree models? If I try to create a `GuestModel` that doesn't inherit from `ModelBase`, I get TS errors in the `createStoreContext`.

**Comment by fullofcaffeine** [comment]
I guess I'm the one that is going against the way mst-gql is supposed to be used. From what I understood, ideally, login would start in a mutation that'd return the logged in user and mst-gql would automatically add it to its users collection, and I could then reference it from `me`. I'm just not sure about the concept of `GuestUser`. 

Do I really need to model it in gql as well? It seems to be a client-side only entity that should be created solely by mobx-state-tree, but I'm not completely sure how to go about that.

**Comment by chrisdrackett** [comment]
on our app we just have a boolean on the root store for if you are logged in or not. I'm not sure if this would work in your case, but we adjust the UI and calls made based on this flag.

**Comment by fullofcaffeine** [comment]
@chrisdrackett Thanks for the insight. That might be the way to go! 

I'm just puzzled on how to mix and match mst-gql and mobx-state-tree models. I created an `Auth` model to gather the `signin`, `signout` actions and added it to the store:

```
Type 'RootStoreType' does not satisfy the constraint 'ModelInstanceTypeProps<{ __queryCache: IOptionalIType<IMapType<IType<any, any, any>>, [undefined]>; }> & { ssr: boolean; __promises: Map<string, Promise<unknown>>; __afterInit: boolean; } & { ...; } & IStateTreeNode<...>'.
  Property '__queryCache' is missing in type 'RootStoreType' but required in type 'ModelInstanceTypeProps<{ __queryCache: IOptionalIType<IMapType<IType<any, any, any>>, [undefined]>; }>'.ts(2344)
MSTGQLStore.d.ts(8, 5): '__queryCache' is declared here.
```

Am I no supposed to mix and match pure mst models and mst-gql models?

```typescript
export const RootStore = RootStoreBase
  .props({
    auth: types.optional(Auth, () => {}),
  })
```
Auth is a model I created and does not inherit from mst-gql`s 'ModelBase`. The problem is that as soon as I add that property, I start getting TS errors:

```

**Comment by fullofcaffeine** [comment]
This issue is already off-track, apologies. I just have two related questions before I close, if you allow me:

1) @chrisdrackett Where do you put your `signin`,`signout` actions? At the RootStore?
2) If I want to extend a mst-gql model with a non-mst-gql model, let's say, by adding a `me` property at the RootStore that points to a non-mst-gql model, how should I do that properly (without triggering the typing errors described in [here](https://github.com/mobxjs/mst-gql/issues/135#issuecomment-548113187)).

Thanks!

**Comment by mweststrate** [comment]
I'm not sure where the error is coming from, but it is the right way to set it up and mix your own models. Also note that it should be `types.optional(Auth, () => ({}))`, not `() => {}` which means something entirely different :)

**Comment by RXminuS** [comment]
Can't we use [getParentOfType](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/API/README.md#getparentoftype) instead?

**Comment by fullofcaffeine** [comment]
@RXminuS Yes, that might be the best solution. I haven't tried it out yet as I chose to just put the actions at the `RootStore` for now, so it's not urgent anymore. I might have a peek at it during the next few days, hence leaving this open for the time being.

However, I'm puzzled by this (somewhat unrelated, but relevant) issue: https://github.com/mobxjs/mst-gql/issues/135#issuecomment-548113187. I was trying to compose a non-mst-gql model that had all the auth actions into the `RootStore` and when I do it, I get a bunch of TS errors:

```
Type 'RootStoreType' does not satisfy the constraint 'ModelInstanceTypeProps<{ __queryCache: IOptionalIType<IMapType<IType<any, any, any>>, [undefined]>; }> & { ssr: boolean; __promises: Map<string, Promise<unknown>>; __afterInit: boolean; } & { ...; } & IStateTreeNode<...>'.
  Property '__queryCache' is missing in type 'RootStoreType' but required in type 'ModelInstanceTypeProps<{ __queryCache: IOptionalIType<IMapType<IType<any, any, any>>, [undefined]>; }>'.ts(2344)
MSTGQLStore.d.ts(8, 5): '__queryCache' is declared here.
```
Looks like it somehow breaks the type interface that expected `__queryCache` to be declared somewhere, but I can't for the sake of me understand those type errors yet :(

I see you also had some issues/insights on how to properly mix "regular" MST with mst-gql models as you described in your 2nd point here: https://github.com/mobxjs/mst-gql/issues/119. Perhaps you know something about this error or encountered a similar issue?

**Comment by fullofcaffeine** [comment]
This isn't a problem for me at the moment. I figured I'd just explicitly access the store using `getParent`  when needed directly at the specific model, so I'm closing this. Feel free to re-open if you find this is still an issue that affects you.
