### ISSUE TITLE
Mixing non-mst-gql models with mst-gql generated models: TS typing woes

### ISSUE THREAD

**Issue by fullofcaffeine** [mobxjs/mst-gql#139]
I originally reported this here: https://github.com/mobxjs/mst-gql/issues/135#issuecomment-548113187. However, since it wasn't really directly related to the purpose of that issue, I'm opening another one for it.

I'm trying to mix `mst-gql` and `mobx-state-tree` models (models that inherit from `MSTGQLObject`). I created an `Auth` (non-`mst-gql`) model to gather the `signin`, `signout` actions and added it to the store:

```typescript
export const RootStore = RootStoreBase
  .props({
    auth: types.optional(Auth, () => ({})),
  })
```
Auth is a model I created and does not inherit from mst-gqls 'ModelBase. The problem is that as soon as I add that property, I start getting TS errors:

```
Type 'RootStoreType' does not satisfy the constraint 'ModelInstanceTypeProps<{ __queryCache: IOptionalIType<IMapType<IType<any, any, any>>, [undefined]>; }> & { ssr: boolean; __promises: Map<string, Promise<unknown>>; __afterInit: boolean; } & { ...; } & IStateTreeNode<...>'.
  Property '__queryCache' is missing in type 'RootStoreType' but required in type 'ModelInstanceTypeProps<{ __queryCache: IOptionalIType<IMapType<IType<any, any, any>>, [undefined]>; }>'.ts(2344)
MSTGQLStore.d.ts(8, 5): '__queryCache' is declared here.
```

If I remove the prop containing the association, then the error goes away.

For now, I got rid of the `Auth` model and just stuffed all the signin-related actions directly in the `RootStore`.

It seems to be a TS-typing only issue. It seems to work fine at runtime.

Does anyone know why this happens?

**Comment by godness84** [comment]
Maybe `Auth` refers somehow to `RootStore`? In this case you have a circular references issue. And when you have it, strange things happen 😄 To solve it, you should break the circularity. How? It depends on the code of the `Auth` model.

**Comment by RXminuS** [comment]
I'm having the same problem but we have over 70 models so it's hard to figure out where the problem is. I was able to "force" the typechecker into submission though by changing `reactUtils.ts`

```ts
export const StoreContext: React.Context<RootStoreType &
  typeof MSTGQLStore.Type> = createStoreContext<any>(React);
```

**Comment by godness84** [comment]
@fullofcaffeine @RXminuS in `mst-gql v0.7.0` TS circular ref issues got solved.

If your extension code adds new circular refs (as it happens in your example, I suppose), declare your reference as `any` (e.g. `types.optional(Auth as any, () => ({}))`) then use the new `withTypedRefs` utility function as you will see in the new generated models.

**Comment by fullofcaffeine** [comment]
@godness84 Thanks for letting us know! I guess we can close this issue, then.
