### ISSUE TITLE
update `localStorageMixin` so that it is possible to clearTimeout

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mst-gql#141]
We've run into a case where a user logs out of our app and we clear local storage only to have `localStorageMixin` repopulate it shortly after due to the timeout. I wonder if there is a way within mst-gql to avoid this case as part of the mixin so a user won't have to worry about it on their end.

**Comment by preetb123** [comment]
`applySnapshot(self, {})` resets the cache. Put it inside a separate action and call it after logout

**Comment by rajeevAgilehub** [comment]
> `applySnapshot(self, {})` resets the cache. Put it inside a separate action and call it after logout

thanks, it worked..
One more question "can we reset a specific data, not all ?"

**Comment by chrisdrackett** [comment]
@rajeevAgilehub you could do this just by updating the object sent into `applySnapshot` to contain only the data from the current store you want to keep.
