### ISSUE TITLE
Auth header when downloading the schema?

### ISSUE THREAD

**Issue by penumbra1** [mobxjs/mst-gql#151]
Hi! 

First of all, thanks for the great tool and the interesting talk!

From what I see in [mst-gql-scaffold.js](https://github.com/mobxjs/mst-gql/blob/202e987c05eca1f2ea30a4c55ee22bebfd35b2f4/generator/mst-gql-scaffold.js#L69), there is currently no way to pass an auth header when fetching the schema from an endpoint.

As Apollo CLI accepts a [--header flag](https://github.com/apollographql/apollo-tooling#apollo-servicedownload-output), would it make sense to add it here?

**Comment by zenflow** [comment]
mst-gql's CLI actually uses apollo's CLI under-the-hood to download the schema:

https://github.com/mobxjs/mst-gql/blob/635da9ffeb9ccf6ed5a6bd30f15271063501d97b/generator/mst-gql-scaffold.js#L66-L70

So this would be pretty trivial to implement.

I'm not opposed to it! :)

**Comment by mwarger** [comment]
I'm going to look at adding this feature.
