### ISSUE TITLE
Understand the workings of mst-gql

### ISSUE THREAD

**Issue by preetb123** [mobxjs/mst-gql#152]
I am really not getting how mst-gql works and handles the cached data. 
How do i get access to it? 
I need to do search, filtering, sorting, grouping etc on that data. Also i may need to modify, delete data from the cache. 

The examples given were not of much help. 
I have created a small example here https://github.com/preetb123/mst-gql-app

`Add/Remove` button adds/removes a book to cart and added book count should be updated 
`Shuffle book` shuffles order of the displayed books
`Sort by title` sorts all items by title
`Sort by author` sorts by author
`Search title` searches the books by title, the list should be updated with items containing the search term

Also how do i get just one item using some filter criteria?

I tried adding `views` & `actions` but i didn't access to store using `self.`, all the data fetch/modify should be triggered from UI and processing done in the models.

Could someone please guide me.

@elie222

**Comment by chrisdrackett** [comment]
Hi @preetb123 are you familiar with MST itself? If not that is a good place to start: https://github.com/mobxjs/mobx-state-tree

If you are familiar, I would say you want to add most of the above as views and actions on the RootStore model here: https://github.com/preetb123/mst-gql-app/blob/master/src/models/RootStore.ts

I think our twitter example is a good place to look for info about extending models: https://github.com/mobxjs/mst-gql/blob/master/examples/3-twitter-clone/src/app/models/RootStore.ts

Let us know if you have any other questions!

**Comment by preetb123** [comment]
thanks @chrisdrackett, i was able to use RootStore.ts to add app specific behaviour using views and action. I have updated the example https://github.com/preetb123/mst-gql-app.
How can i get access to `store` outside of react class or stateless function?

**Comment by elie222** [comment]
You can just import and access wherever you like:

```
import { RootStore } from '....'
RootStore.xyz
```

**Comment by preetb123** [comment]
@elie222 i am not sure if the above way of using `RootStore.xyz` is correct. I don't get access to any method or prop on `RootStore`. 

What i want to achieve is to get `AsyncStorage` in place of `localStorage` here https://github.com/mobxjs/mst-gql/blob/master/examples/4-apollo-tutorial/client/src/index.js#L17

**Comment by chrisdrackett** [comment]
it is possible to pass in your own storage method:

https://github.com/mobxjs/mst-gql#use-with-react-native

**Comment by chrisdrackett** [comment]
you need to initialize the store somewhere, like https://github.com/mobxjs/mst-gql/blob/master/examples/4-apollo-tutorial/client/src/index.js#L23 and then from that you should have access to whatever you need.

**Comment by chrisdrackett** [comment]
closing this for now but feel free to open a new issue if you run into issues!
