### ISSUE TITLE
Better generated names

### ISSUE THREAD

**Issue by beepsoft** [mobxjs/mst-gql#157]
I would like to discuss whether we could generate better names for the MST models and whether it could be made configurable. I feel that it would provide better developer experience overall. 

TLDR; these are my suggestions:
1. Allow generation of Javascript conform names for graphql names with lowercase, underscores, snake_case, etc.
2. For a graphql type called `Todo` generate a typescript interface called `Todo` instead of `TodoModelType`
3. For graphql enum type names ending in `Enum` don't generate an additional `Enum` postfix, ie. instead of `TodoPriorityEnumEnum` just have `TodoPriorityEnum`
4. Proper pluralization for root type collection names and use camelCase, ie. if the root type is "PostBox" the root collection name should not be `postboxs` but `postBoxes`
5. I have a [PR](https://github.com/mobxjs/mst-gql/pull/155) covering point 1 and 4

And the details:

as usual, most of my "problems" come from using [Hasura](https://hasura.io/), which generates graphql models based on Postgresql types, which are all lowercase and are usually in snake_case. 

Generated Typescipt types and mst-gql models just look very ugly and not javascript-like and it is really uncomfortable to use these generated symbols. For example, for this [schema](https://gist.githubusercontent.com/beepsoft/84a64102a80a3ac7eb1f656b64fc2af8/raw/8c645994a5411a9f9d5cbea48677615d70b08562/schema.graphl)  I get mst-gql models like this:

```typescript
import { Instance } from "mobx-state-tree"
import { polls_aggregate_fieldsModelBase } from "./polls_aggregate_fieldsModel.base"

/* The TypeScript type of an instance of polls_aggregate_fieldsModel */
export interface polls_aggregate_fieldsModelType extends Instance<typeof polls_aggregate_fieldsModel.Type> {}

/* A graphql query fragment builders for polls_aggregate_fieldsModel */
export { selectFrompolls_aggregate_fields, polls_aggregate_fieldsModelPrimitives, polls_aggregate_fieldsModelSelector } from "./polls_aggregate_fieldsModel.base"

/**
 * polls_aggregate_fieldsModel
 */
export const polls_aggregate_fieldsModel = polls_aggregate_fieldsModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
```

OK, so, the problem with generated names I see is two fold:
1. Providing new aliases for the types provided by the input graphql model
2. Better overall naming strategy for the MST models and types

The first problem is also addressed by other graphql generation tools, namely [graphql codegen](https://graphql-code-generator.com/docs/plugins/typescript).  It has options to use different casing in the generated types. 

It looks like this:

```yaml
config:
  namingConvention:
    typeNames: change-case#pascalCase
    transformUnderscore: true	
```

With these settings it would be possible to have for the type `polls_aggregate_fields` this in mst-gql:

```graphql
import { Instance } from "mobx-state-tree"
import { PollsAggregateFieldsModelBase } from "./PollsAggregateFieldsModel.base"

/* The TypeScript type of an instance of PollsAggregateFieldsModel */
export interface PollsAggregateFieldsModelType extends Instance<typeof PollsAggregateFieldsModel.Type> {}

/* A graphql query fragment builders for PollsAggregateFieldsModel */
export { selectFromPollsAggregateFields, pollsAggregateFieldsModelPrimitives, PollsAggregateFieldsModelSelector } from "./PollsAggregateFieldsModel.base"

/**
 * PollsAggregateFieldsModel
 */
export const PollsAggregateFieldsModel = PollsAggregateFieldsModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
}
```

And this could work fine in mst-gql as well, I even created a PR for this to prove: https://github.com/mobxjs/mst-gql/pull/155

It doesn't provide detailed configuration like graphql codegen it only support the naming convention "js", which means PascalCase type names and camelCase names for other names.

The other problem I see is the naming strategy mst-gql generator uses currently.

1. For graphql type called `Todo` it generates an MST model `TodoModel`, which is fine, however the typescript type it generates looks like this:
  ```
  export interface TodoModelType extends Instance<typeof TodoModel.Type> {} 
  ```
  Why not just call it `Todo` like this?
  ```
  export interface Todo extends Instance<typeof TodoModel.Type> {}
  ```
  It seems more natural for me

2. If an enum type in graphql already ends with `Enum` we should not add an extra `Enum` to the generated name. Eg. for this

```graphql
enum TodoPriorityEnum {
	LOW
	HIGH
	MEDIUM
}

type Todo {
	id: ID,
	text: String,
	complete: Boolean,
	priority: TodoPriorityEnum
}
```

We would get a TodoPriorityEnumEnum.ts with

```typescript
import { types } from "mobx-state-tree"

export enum TodoPriorityEnum {
  LOW="LOW",
  HIGH="HIGH",
  MEDIUM="MEDIUM"
}

export const TodoPriorityEnumEnum = types.enumeration("TodoPriorityEnum", [
  "LOW",
  "HIGH",
  "MEDIUM",
])
```

3. Root collection names are just `rootTypeName.toLowerCase()+"s"` This is fine in most cases, however in case of exceptions eg. if the root type is "PostBox" the root collection name becomes `postboxs` instead of `postboxes` but actually it would be better as `postBoxes`. In my [PR](https://github.com/mobxjs/mst-gql/pull/155) I tried to solve this as well.

These changes would be breaking changes but we could make an option which would generate these names and keep the old naming strategy as the default.

What do you think?

**Comment by beepsoft** [comment]
@chrisdrackett, @zenflow any ideas, comments? I would be glad to proceed with this and implement what is agreed on.

There are 2 issues that can be discussed and resolved separately:

1. **Allow new aliases for the types provided by the input graphql model**. This would be an optional feature with a command line option (my current implementation uses `--namingConvention`).
1. **Better overall naming strategy for the MST models and type**s. This would cause breaking changes in  the generated model files, but would result in nicer type/model names.

**Comment by chrisdrackett** [comment]
So for issue 1 my opinion is to not add an option and just have this transformation be the default. This does not apply to my codebase as our models already come in "clean" but as a user I would much rather a library generate `PollsAggregateFieldsModelBase` than `polls_aggregate_fieldsModelBase`. Unless others feel strongly that we should add the option that would be my vote. As we're pre-1.0 I think its ok to introduce a change like this now, but I could always be wrong :)

For issue 2 I'm also on board. I think all the changes outlined (`TodoModelType` -> `Todo`, `TodoPriorityEnumEnum` -> `TodoPriorityEnum`, `postboxes` -> `postBoxes`) are good and we should implement them. Same argument about pre-1.0 as above.

**Comment by beepsoft** [comment]
@zenflow had some concerns with changing the names to something different than the ones provided by the schema:

> Why wouldn't we want to use the exact tokens from the graphql schema in our js code? What benefit does a different style of naming offer?

I think this is valid to have the same (similar) names as in the schema. It is a matter of taste. I myself prefer to see idiomatic Javascript/TypeScript symbols. That's why I think having a command line option to configure this is a good option.

**Comment by beepsoft** [comment]
I went ahead and implemented all the features above in PR #155:

1. Proper pluralization in RootStore props
1. `TodoModelType` -> `Todo`
1. `TodoPriorityEnumEnum` -> `TodoPriorityEnum` (the file is now called `TodoPriorityEnumModel.ts` when this is defines)
1. `--namingConvention js` to change snake_cases to PascalCase type names and camelCase field/function names
1. Added support for  this https://spec.graphql.org/June2018/#example-e2969. Ie. the Query/Mutation/Subscription type is not necessarily called Query/Mutation/Subscription (as it was assumed in mst-gql before) but could be defined using a
```
schema {
  query: query_root
  mutation: mutation_root
  subscription: subscription_root
}
```
definition (Hasura uses this, for example).

All these features can be tried by using this npm package for the above PR:

https://github.com/beepsoft/mst-gql#mst-gql-v0.7.1-pr155-gitpkg

**Comment by mwarger** [comment]
@beepsoft Cheers to you!  I was searching around this evening wondering why my actions weren't generating for my Hasura API.   Thanks for the PR!

**Comment by beepsoft** [comment]
@chrisdrackett  as #155 has been merged we can close this issue, right?

Ps.: version number in package.json is still 0.7.1

**Comment by chrisdrackett** [comment]
@beepsoft sorry about that! it is released now! Lots going on :)
