### ISSUE TITLE
Require Cycle

### ISSUE THREAD

**Issue by Aryk** [mobxjs/mst-gql#164]
When we have types that are self-referencing, I get a warning:

```
Require cycle: src/app/models/UserModel.ts -> src/app/models/UserModel.base.ts -> src/app/models/UserModel.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

I'm not sure if this will result in an error down the line, but I get an annoying warning message on bootup. Any recommendations on how I can fix this?

For now I'm using "YellowBox.ignoreWarning" but I'm still getting a bunch of yellow in the console.

**Comment by chrisdrackett** [comment]
we get this as well in react-native. It should be harmless. There are potential ways that our models could be generated in a way to avoid this that @RXminuS and others have been looking at, so if we can get a solid PR on the matter this might be fixable!

**Comment by Aryk** [comment]
Ok, got it, good to know I'm not the only one experiencing this.

Do you happen to know how I can remove these warnings from the console? I tried overriding the console.warn/error/info/log methods but I'm not able to intercept those messages.

**Comment by chrisdrackett** [comment]
@Aryk look here for some info: https://reactnative.dev/docs/debugging#warnings

**Comment by Aryk** [comment]
Hey Chris, I think as my application gets larger and larger, this hurting Typescripts ability to find references to things. 

Sometimes, I run the typescript compiler and there are no errors, other times there are like 50 errors, having to do with not finding methods from the MSTGQL store.

I'm sure it has something to do with the dependencies. How do I get around needed to require types, and models in other models in MST-GQL?

**Comment by Aryk** [comment]
@chrisdrackett 

I've confirmed that the require cycles are eminating from the models.

I have a suggestion. Why don't the *base files also export the type's that they already import?

For example:

User.base
```ruby
import { NetworkModel, NetworkModelType } from "./NetworkModel"
```
^^ It already does that automatically because networks is an association on the user.

Then in UserModel you can do 

```ts
import {NetworkModelType from "src/app/models/UserModel.base";

```

instead of needing to add another required file.

I'm not 100% sure that this would make a difference, but I think it would since there is less interacting of dependencies which can cause the TS compiler off guard.
