### ISSUE TITLE
LIST always interpreted as required

### ISSUE THREAD

**Issue by Aryk** [mobxjs/mst-gql#165]
These two definitions will both result in required values for `ids`, in other words, I cannot omit the value from my query. One of them has "ids" as required and other does not. However, even if I do not make `ids` required, the typescript definition will not have a "?" on it, making it optional ie `variables: { ids: string[] }`. It should be `variables: { ids?: string[] }` when it is not required. This will work correctly when it is not a LIST, and just a normal scalar. I now have to add `{ids: undefined}` so that my TS compiler does not complain.

```
    {
                  "name": "ids",
                  "description": null,
                  "type": {
                    "kind": "LIST",
                    "name": null,
                    "ofType": {
                      "kind": "NON_NULL",
                      "name": null,
                      "ofType": {
                        "kind": "SCALAR",
                        "name": "ID",
                        "ofType": null
                      }
                    }
                  },
                  "defaultValue": null
                }
```

AND

```
 {
                  "name": "ids",
                  "description": null,
                  "type": {
                    "kind": "NON_NULL",
                    "name": null,
                    "ofType": {
                      "kind": "LIST",
                      "name": null,
                      "ofType": {
                        "kind": "NON_NULL",
                        "name": null,
                        "ofType": {
                          "kind": "SCALAR",
                          "name": "ID",
                          "ofType": null
                        }
                      }
                    }
                  },
                  "defaultValue": null
                }
```

**Comment by chrisdrackett** [comment]
I could be wrong, but I think ID is required as a way to connect the item to the store. Without the id and type there isn't a way to know what local item to connect to the one coming down from the server.

**Comment by Aryk** [comment]
To clarify, "ids" is an argument I defined for the query method on the graphql service. Yes, if provided, it must be an array with "ID" inside of it. However, I've specified that "ids" the array is optional, meaning you don't have to pass in the array.

This is not supported by mstgql

**Comment by Aryk** [comment]
This issue has been really annoying, curious if others have experienced it. Im using Ruby and for example I have:

```ruby
    field :activities, [Types::ActivityType], null: false do
      argument :creator_ids, [ID], required: false
    end
```

And yet, if I don't do creatorId: undefined, the TS compiler will throw an error.

**Comment by Aryk** [comment]
@chrisdrackett any chance we can push this through. It's been sitting around for two months.

To repeat. This is not a nice-to-have. MST-GQL is not honoring the graphQL spec.

I have a PR ready to go with tests that just need to be accepted.

cc @mobxjs

**Comment by sanketsahusoft** [comment]
I am not sure if we can skip IDs as it is primarily used by the RootStore for references.

**Comment by Aryk** [comment]
I think my example confused you and @chrisdrackett . Let me show you a better example.

```ruby
    field :activities, [Types::ActivityType], null: false do
      argument :creator_ids, [ID], required: false
      argument :show_past, Boolean, required: false
      argument :starting_from, GraphQL::Types::ISO8601DateTime, required: false
      argument :order, ActivityOrderType, required: false
    end
```
MST will parse these arguments and output:

```ts
 queryActivities(variables: { creatorIds: string[], showPast?: boolean, startingFrom?: any, order?: ActivityOrder }
```

Notice how both creator_ids and show_past in Ruby are both "required: false". ++However++, in Typescript with this library it will output +only+ showPast as an optional param, when really it should be:

```ts
 queryActivities(variables: { creatorIds?: string[], showPast?: boolean, startingFrom?: any, order?: ActivityOrder }
```

Does this make sense now what is wrong?

Look at the spec that I wrote in the PR and it will be very obvious what is wrong.
