### ISSUE TITLE
Generating React hooks specific to operations

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mst-gql#18]
Regarding the code generation, I actually do have a custom generator for `graphql-code-generator` which generates fully typed hooks for each graphql operation. I am not sure yet how it would look like here, but a similar alternative would be really nice.

```ts
export function useQResolveLocation(
  variables?: QResolveLocationVariables,
  baseOptions?: Hooks.QueryHookOptions<QResolveLocationVariables>,
) {
  return Hooks.useQuery<QResolveLocationQuery, QResolveLocationVariables>(
    QResolveLocationDocument,
    variables,
    baseOptions,
  )
}
```

I am using prefixes Q, M, S, F for my `*.gql` documents and based on that I can distinguish those easily.

_Originally posted by @FredyC in https://github.com/mobxjs/mst-gql/issues/13#issuecomment-496870294_

**Comment by mweststrate** [comment]
Could you post some before and after examples with the actual api you have in mind from component perspective? 

* A benefit of using hooks is that they can nicely be tree-shaken

Some downsides I see:
* Cant reuse them from imperative logic
* They don't provide a way to do some pre / or post processing logic, while keeping all query logic in the store allows for a central place to organize these things

**Comment by elie222** [comment]
Sample output when using graphql-code-generator: https://graphql-code-generator.com/docs/plugins/typescript-react-apollo#withhooks-boolean-default-value-false

```gql
export const ResolveAlertDocument = gql`
  mutation ResolveAlert($_id: String!) {
    resolveAlert(_id: $_id) {
      _id
      riskLevel
    }
  }
`
export type ResolveAlertMutationFn = ReactApollo.MutationFn<
  ResolveAlertMutation,
  ResolveAlertMutationVariables
>

export function useResolveAlertMutation(
  baseOptions?: ReactApolloHooks.MutationHookOptions<
    ResolveAlertMutation,
    ResolveAlertMutationVariables
  >
) {
  return ReactApolloHooks.useMutation<ResolveAlertMutation, ResolveAlertMutationVariables>(
    ResolveAlertDocument,
    baseOptions
  )
}
```

**Comment by FredyC** [comment]
This is based on Apollo (obviously) and I even have a custom fork of `react-apollo-hooks` to improve DX.

I haven't really tried this package in action to see what it generates. Nor I read that whole README (😮). It does look intriguing on a surface, but I have a very well established approach with hooks I don't see much of gain from stuffing it into mobx models right now.

> * Cant reuse them from imperative logic

For each query, I am also generating an _executable_ variant that runs `client.query` instead of `client.watchQuery`.

```ts
const [resolve] = useExecutableQResolveLocation()
const onClick = () => {
  resolve({ variables })
}
```

> * They don't provide a way to do some pre / or post processing logic, while keeping all query logic in the store allows for a central place to organize these things

Well, you can always wrap such generated hook into a custom hook to provide additional logic. I am not sure what exactly you have in mind.

**Comment by mweststrate** [comment]
Ok, sounds like this is not a proposal based on an actual problem / usage. Closing for now.
