### ISSUE TITLE
Circular dependencies problem

### ISSUE THREAD

**Issue by Matth10** [mobxjs/mst-gql#190]
## Issue
We are currently using graphql with almost 100 of root types. After the generation of all the `models.base` and `model` we were having this error : `SellerModelbase\_WEBPACK_IMPORTED_MODULE_0_.SellerModelBase is undefined`.

## Reason
After an investigation on that I realized we have a lot of circular dependencies. 
<img width="747" alt="Screen Shot 2020-03-20 at 8 27 42 AM" src="https://user-images.githubusercontent.com/29732250/77178707-b39f2480-6a84-11ea-8b04-edbf11cf3466.png">

**Comment by chrisdrackett** [comment]
this has been an ongoing issue. I know @RXminuS had some ideas around this, but I'm not sure what come of them. I know there has been talk of flattening some of the generated structure so we end up with less generated files. This might help some with the circular dependencies.
