### ISSUE TITLE
Further processing data from store in useQuery hook and using it from SSR

### ISSUE THREAD

**Issue by fullofcaffeine** [mobxjs/mst-gql#197]
Hey everyone,

This is related to the previous [issue](https://github.com/mobxjs/mst-gql/issues/191) I opened, but please disregard that one as it ended up being too confusing. 

Allow me to describe what I want to do instead and perhaps more experienced fellow `mst-gql`'ers could help me:

So, I have a React hook that looks like this:

```
import { delinearizeTodos } from './tree-helpers';

 const Todos = observer((props) => {
  const { data }  = useQuery(store =>
      store.queryTodoItems({}, item => item.id.parentId.title).then(delinearizeTodos);
  )

  return (
       <SortableTree treeData={data}/>
   )
}
```

To briefly describe what this hook does:

1) It fetches a flat representation of an adjacency list tree from the server...
2) ...And `then` it proceeds to delinearize it (turn it back into a tree data structure);
3) And passes it over to the [<SortableTree>](https://github.com/frontend-collective/react-sortable-tree) component;

This hook component is meant to be SSRed too.

So I'm having two problems here:

1) Chaining the `then(delinearizeTodos)` in the `Query` object instance returned by `queryTodoItems` makes the `data` in the object returned `undefined`. If I remove that `then`, then the `data` is populated as expected (on the client only, though, see `2` below). How can I further process the data before it's populated in the `data` object and returned by the `useQuery` hook? 
2) The `useQuery` doesn't seem to work when the component is SSRed. When running from node, it always `data` as `undefined`. This results in the tree not being rendered in the server, a requirement I have for this component. Am I supposed to use a class component if I want the component to fetch data when it's SSRed? Or am I missing something?

Any help insights would be greatly appreciated!

**Comment by mattiasewers** [comment]
@fullofcaffeine this does not seem to be supported atm, see how its done in a similar way in examples:

https://github.com/mobxjs/mst-gql/blob/54a020f07e11313d91288625091bed8e02e2fed7/examples/3-twitter-clone/src/app/models/RootStore.ts#L43

so its recommended to do it the store instead.

**Comment by fullofcaffeine** [comment]
Ah, great. This pattern might as well work for me. I'll try that out.

To further elaborate on this issue, though:

I actually might've over-complicating things a bit, but perhaps it could be used to trigger the discussion for further improvement. Maybe there's a way to improve the Query API to allow "filters/middlewares"? Please let me know if the following makes sense to you:

These filters could run at a point in the lifecycle where the data is still raw and not yet converted to mst objects. In my case, it was easier to delinearize the linearized tree object returned by GraphQL at this point rather than after it was already typed into mst objects.

Here's the diff to what I did locally to `mst-gql` js source code:

```diff
diff --git a/node_modules/mst-gql/dist/mst-gql.module.js b/node_modules/mst-gql/dist/mst-gql.module.js
index c8dcb93..3ad3f54 100644
--- a/node_modules/mst-gql/dist/mst-gql.module.js
+++ b/node_modules/mst-gql/dist/mst-gql.module.js
@@ -138,7 +138,7 @@ var fastJsonStableStringify = function (data, opts) {
 };
 
 var isServer = typeof window === "undefined";
-var Query = function Query(store, query, variables, options) {
+var Query = function Query(store, query, variables, options, filter) {
   var this$1 = this;
   if ( options === void 0 ) options = {};
 
@@ -148,6 +148,7 @@ var Query = function Query(store, query, variables, options) {
   this.loading = false;
   this.data = undefined;
   this.error = undefined;
+  this.filter = filter ? filter : d => d;
 
   this.refetch = function () {
     return Promise.resolve().then(action(function () {
@@ -224,7 +225,7 @@ Query.prototype.fetchResults = function fetchResults () {
   if (existingPromise) {
     promise = existingPromise;
   } else {
-    promise = this.store.rawRequest(this.query, this.variables);
+    promise = this.store.rawRequest(this.query, this.variables).then(this.filter);
 
     this.store.__pushPromise(promise, this.queryKey);
   }
@@ -346,10 +347,10 @@ var MSTGQLStore = types.model("MSTGQLStore", {
     }
   }
 
-  function query(query, variables, options) {
+  function query(query, variables, options, filter) {
     if ( options === void 0 ) options = {};
 
-    return new Query(self, query, variables, options);
+    return new Query(self, query, variables, options, filter);
   }
 
   function mutate(mutation, variables, optimisticUpdate) {
```

And I used it like this:

```
const Todos = observer((props) => {
   const { data, loading }  = useQuery(store => store.queryTodoItems(delinearizeTodos));
   // Now when `data` resolves, it has my mst-typed nested tree structure, as expected
});
```

Where `delinearizeTodos` is the function that takes the raw linear tree data structure returned from my GraphQL query and turns into a nested tree data structure (wish I could just return the whole nested tree from GraphQL, but it's not [possible](https://github.com/graphql/graphql-spec/issues/91)). In this case, the data sent to `delinearizeTodos` is the raw json data returned by GraphQL. 

I haven't fully explored the benefits of doing it at this point in the lifecycle, and I'm sure I could do that like you suggested in the Twitter example with mst objects, but it was certainly easier and I guess it has the benefit of re-using all the caching logic etc.

1) That being said, I don't like the API and it was a kind of desperate attempt at solving the issue. I'll probably discard it and use the approach suggested but maybe we could discuss a proposal to add filters/middlewares like along these lines?

2) And for further processing the typed mst data returned from the Query object, is there a specific reason the `then` interface can't be chained? It just feels natural chain queries for further processing of the data, instead of pushing to another closured array variable, like in the Twitter example above. Was that the intended design?

**Comment by chrisdrackett** [comment]
@fullofcaffeine a lot of this is possible within your MST models. Instead of doing this kind of work in the hook you can do it within your models using a reaction or a computed. This does mean that you don't actually use `data` from the useQuery hook and instead would be doing something like:

```
const { store }  = useQuery(store =>
      store.queryTodoItems({}, item => item.id.parentId.title);
  )

const data = store.delinearizeTodos
```

or similar.

Does that help? I might also be missing something...

**Comment by fullofcaffeine** [comment]
Hi @chrisdrackett 

Yeah, that seems to be working. Thanks! I'm still kind of puzzled on why the `then` interface doesn't allow for chaining, it seems kind of counter-intuitive, or perhaps I'm missing something? 

I'm closing this issue as this seems to solve the issue.
