### ISSUE TITLE
Offline first approach

### ISSUE THREAD

**Issue by sanketsahusoft** [mobxjs/mst-gql#198]
First of all, thanks for the great work! I am looking at offline first strategies.

Strategy: Everything local + sync to remote later
• Create objects locally (unique + reliable IDs), merge in RootStore, mark them dirty.
• Keep a tick that syncs the dirty objects.

Do you think this is a good approach?

**Comment by special-character** [comment]
Hey @sanketsahusoft, this is exactly what @chrisdrackett and I do for the application we are working on now. We use the `mst-gql` `ModelBase` to keep a queue of actions that need to be synced. We use a [reaction](https://mobx.js.org/refguide/reaction.html) to react to changes in the online state and the queue state. If either of those change we check if we need to sync and go through the queue.

This 2 part post from Michel served as inspiration for our offline support: [Distrubuting state changes using snapshots, patches, and actions](https://medium.com/@mweststrate/distributing-state-changes-using-snapshots-patches-and-actions-part-1-2811a2fcd65f)

**Comment by barbalex** [comment]
Combining this with offline usage ~~would be~~ is huge.

I think you should place this prominently on the readme. It could attract a lot of interest and hopefully even some willing to help develop this further. To make it accessible to humble devs like me.

I am now searching for "easy" options to make some of my apps offline capable without having to go all in into [CouchDB](https://docs.couchdb.org/en/stable/replication/index.html) which is not an option for app with 50+ related tables. 

The other two options I have found so far are:
- CouchDB-style data revisioning: https://hasura.io/blog/couchdb-style-conflict-resolution-rxdb-hasura/
- persisted operations using offix (https://offix.dev)
- maybe even a combination

This issue looks like an alternative way to persist operations. While exchanging apollo for mobx-state-tree. Which I personally _love_. To be honest, apollo state management sucks when compared to mst (while the querying is great). Which is why all my apps use mst for local app state. And my electron apps (based on SQLite without GraphQL) use it for local data state too.

**Comment by chrisdrackett** [comment]
@special-character I wonder if we could easily put our take on offline into one of the mst-gql examples as a first step?

**Comment by fullofcaffeine** [comment]
I'd love to check it out!

**Comment by barbalex** [comment]
This seems a good starting point: https://github.com/mobxjs/mobx-utils/blob/master/src/queue-processor.ts

**Comment by barbalex** [comment]
o.k., got it: a reaction is much simpler 👍

**Comment by special-character** [comment]
It seems there is a decent amount of interest in this approach. I could probably update one of the examples or create a new one to show how we currently do this.

I created this Issue to do that. I can do it but might not get to it right away. 

https://github.com/mobxjs/mst-gql/issues/228

**Comment by barbalex** [comment]
I ended up building a new Type named "Query":

```js
import { types } from 'mobx-state-tree'

export default types.model('Query', {
  name: types.string,
  variables: types.maybeNull(types.string, null),
  // a query to run after the first
  // to refresh the data from the server
  callbackQuery: types.maybeNull(types.string, null),
  callbackQueryVariables: types.maybeNull(types.string, null),
})

```

Which is used in the model:
```js
pendingQueries: types.optional(types.array(QueryType), [])
```

and a reaction:
```js
reaction(
  () => `${self.pendingQueries.length}/${self.online}`,
  () => {
    if (self.online) {
      // execute operation
      const query = self.pendingQueries[0]
      if (query) {
        const {
          name,
          variables,
          callbackQuery,
          callbackQueryVariables,
        } = query
        try {
          variables ? self[name](JSON.parse(variables)) : self[name]()
        } catch (error) {
          // Maybe do it like superhuman and check if network error
          // then retry and set online without using tool?
          return
        }
        // idea: query to refresh the data updated in all used views (tree...)
        if (callbackQuery) {
          try {
            callbackQueryVariables
              ? self[callbackQuery](JSON.parse(callbackQueryVariables))
              : self[callbackQuery]()
          } catch (error) {
            return
          }
        }
      }
      // remove operation from queue
      self.pendingQueries.shift()
    }
  },
)
```

Here part of a mutation in a form:
```js
addPendingQuery({
  name: 'mutateInsert_herkunft',
  variables: JSON.stringify({
    objects: [newObject],
    on_conflict: { constraint: 'herkunft_pkey', update_columns: [] },
  }),
  callbackQuery: 'queryHerkunft',
  callbackQueryVariables: JSON.stringify({
    where: { id: { _eq: id } },
  }),
})
```

Surely this is just a first attempt. But it seems to work 😄

**Comment by special-character** [comment]
@barbalex That seems really close to what we are doing as well. Currently, we only remove the operation from the queue if it succeeded. One thing we found useful was to add a scheduled reaction to run every minute to catch cases where the request fails. Something like this:

```
/**
       * In case the above didn't run (say the user was offline)
       * check every so often if we're good to sync, and if so, sync!
       */
      const timeListenerDisposer = reaction(getSyncReactionParams, sync, {
        scheduler: (run) => {
          setInterval(run, 60000) // 60000 = one minute
        },
      })
```

**Comment by barbalex** [comment]
@special-character Thanks a lot, I didn't know the scheduler option.

@others:
You need to run the function once before setting the interval or it will never run immediately:
```js
scheduler: (run) => {
  run() // ensure it runs immediately if online
  setInterval(run, 60000) // 60000 = one minute
}
```
