### ISSUE TITLE
Add a Roadmap / Projects

### ISSUE THREAD

**Issue by sanketsahusoft** [mobxjs/mst-gql#199]
I would like to contribute, do we have a list of priorities that I can refer to?

**Comment by Aryk** [comment]
Hi @sanketsahusoft could you help me push through this PR for this glaring and common problem?

https://github.com/mobxjs/mst-gql/issues/165

**Comment by chrisdrackett** [comment]
hi @sanketsahusoft! We don't currently have a roadmap, but one would probably be a good idea. There are some bigger things like how we generate files (#13) and smaller things you can find in our issues list. I'm going to go through and clean it a bit now.

**Comment by chrisdrackett** [comment]
added a roadmap here, now to fill it out ;)

https://github.com/mobxjs/mst-gql/projects/1

**Comment by sanketsahusoft** [comment]
Thanks, @chrisdrackett! Let me add a few more things to the roadmap!

**Comment by Aryk** [comment]
Hey I don't have access to the roadmap, but can we please fix the coupling of actions occuring in a constructor function? 😄 

For example:

```ts
const {loading, data, error, query} = useQuery(store => store.mutateLater())

const runMutationOnButtonClick = () => query.refetch(); ????
```

Oops! mutate already ran when I loaded the Component. 😢 

It really should be decoupled so you can do:

const {loading, data, error, query} = useQuery(store => store.mutateLater(input: {blah}, undefined, {runLater: true}))

const runMutationOnButtonClick = () => query.execute() // or whenever I'm ready to do.

You can decouple it now by pulling out the store, but then you need to redefine the state for `loading` `data` `error`...whats the point then of having MST-GQL?

**Comment by mattiasewers** [comment]
@Aryk https://github.com/mobxjs/mst-gql#mutations

**Comment by Aryk** [comment]
Oh so that's what setQuery is for...got it. Will try it out!

**Comment by Aryk** [comment]
Another special required 😄 

Any chance we can create typescript interfaces for the inputs into the queries? Right now, they are just hardcoded in and not reusable...If I want to pass in variables into a component that will make its way into a query or mutation, I have to write out the types again manually.

**Comment by chrisdrackett** [comment]
open an issue or a PR :D
