### ISSUE TITLE
Gqless

### ISSUE THREAD

**Issue by lishine** [mobxjs/mst-gql#203]
Have you seen this? Can be a combination...

**Comment by chrisdrackett** [comment]
this is pretty cool, but off the bat I don't have any thoughts on how this could be combined with mst-gql. To me the big difference is with mst-gql you are not really doing any graphQL in your components, but instead are interacting mostly with mst. That being said, I think we would be down for suggestions if there are features you think would fit well with mst-gql.

I'm going to close this for now, but feel free to open a new issue if you have specific feature suggestions!
