### ISSUE TITLE
Is createUseQueryHook supposed to have a TS parameters passed in?

### ISSUE THREAD

**Issue by Aryk** [mobxjs/mst-gql#213]
Autogenerated file looks something like this:

```ts
/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { createStoreContext, createUseQueryHook } from "mst-gql"
import * as React from "react"
import { RootStore, RootStoreType } from "./RootStore"

export const StoreContext = createStoreContext<RootStoreType>(React)

export const useQuery = createUseQueryHook(StoreContext, React)
```

But in the library there is:

```ts
export declare function createUseQueryHook<STORE extends typeof MSTGQLStore.Type>(context: React.Context<STORE>, React: typeof ReactNamespace): UseQueryHook<STORE>;
```

Shouldn't the autogenerated file do something like `createUseQueryHook<RootStore>`;

Maybe it was intended to be that way?

**Comment by Aryk** [comment]
My guess is, it's  supposed to be:

```ts
export const useQuery = createUseQueryHook<RootStoreType>(StoreContext, React)
```

**Comment by chrisdrackett** [comment]
`STORE` here is a generic and is inferred from the context. So the `RootStoreType` in your example is what comes in for `STORE` you can override it if you want, but by default it should just work®

**Comment by Aryk** [comment]
That's interesting. My understanding is that RootStoreType extends and adds those extra methods like "store.mutate<method>" etc. I probably don't understand TS well enough. My thought is that it should only be able to find the methods from the STORE generic, which has just #query #mutate and a few others, but not those automatically generated methods in the RootStore.Base file. For that you would need to pass in something that extends from the top level STORE which would be RootStoreType... *shrugs*

**Comment by chrisdrackett** [comment]
right, but `StoreContext` is being passed in here which is setup like `createStoreContext<RootStoreType>` this effectively says that the `STORE` === `RootStoreType` and you are off to the races!
