### ISSUE TITLE
Type script error when returning a mutation in an action

### ISSUE THREAD

**Issue by Aryk** [mobxjs/mst-gql#216]
I created an action which does a mutation, but when I "return" from it, it blows up my Typescrip checker and it cannot no longer find the methods on many of the MSTGQL models:

```ts
    update: (user: InputUserUpdate, opts: {resultSelector?: any, optimisticUpdates?: any} = {}) => {
 
      return self.store.mutateUserUpdate(
        {input: {user}},
        undefined,
        opts.optimisticUpdates,
      ).currentPromise().catch(handleApiError);
    },
```

Has anyone else experienced this. If I remove the "return" all the typescript errors go away.

My guess is it has something to do with some circular referencing because I have a lot models and got alot of those warnings, but Im not sure why "returning" in of itself is causing the issue.

I have no clue how to prevent that though since MST gql auto-generates these circular references. Not sure if that is the cause though.

**Comment by Aryk** [comment]
Ok, if I specify a return type like "any", the errors go away. Anybody have any idea why this was happening?

**Comment by chrisdrackett** [comment]
yeah, this is our old friend circular I'd wager. The best way to combat this is to explicitly type your action returns atm.

**Comment by MaxSvargal** [comment]
Just specify a return type of the function.
