### ISSUE TITLE
Typing and setQuery when initial useQuery undefined

### ISSUE THREAD

**Issue by axelnormand** [mobxjs/mst-gql#221]
Hello
Quick question.....I was just curious on the best pattern to type a useQuery (particularly data) when the initial useQuery is undefined (ie i dont want anything to run on mount)?
Then i use setQuery later in the code (eg when press button)

```
   // no query on mount but data now not typed
    const {data, loading, error, store, setQuery} = useQuery(); 
    ...
    // want to use data and loading here
    ...
    if (loading) return "Loading";
    return (
    <>
     <Button onPress={() => setQuery(store.mutateAThing()}/>
     { data && <Text>Hello ${data.username} </Text>}
   </>
   )
```

ps very much enjoying creating a new UI with mst-gql and all the typing goodness so many thanks for the library

**Comment by chrisdrackett** [comment]
this is a good question that I don't have a great answer for.

The way we deal with this in our app is that we don't actually access `data` at all and just access `store` which, at the end of the day, contains whatever came down as data. That being said, if this does not work for you we might need to look into a way of typing data. My guess is that it will have to be somewhat manual as I don't think there is a way to link the params of `setQuery` with the above `useQuery`

**Comment by axelnormand** [comment]
Thanks for the reply. Good to know.
Similar to what you suggested i think , the pattern i used instead was to use store (from useContext) in a wrapper component and pass props to a child presentation component.
Not the end of the world.


Could mst-gql perhaps generate a useLazyQuery too which returns the query function to run later like react apollo hooks does?
https://www.apollographql.com/docs/react/data/queries/

**Comment by mattiasewers** [comment]
@axelnormand You can use `setQuery` for that

**Comment by chrisdrackett** [comment]
going to close this for now, but feel free to open a new issue with any further questions or issues!
