### ISSUE TITLE
Add/Update an example to be offline-first

### ISSUE THREAD

**Issue by special-character** [mobxjs/mst-gql#228]
This was brought up first in this issue: https://github.com/mobxjs/mst-gql/issues/198

There is some interest on how to support offline with this library. We should add a new example or update one of them to be offline first. I have done this in another project so I can take a crack at this.

**Comment by krstns** [comment]
Is there any eta regarding this change? This approach becomes more and more popular.

**Comment by special-character** [comment]
I am no longer using this project and don't plan on adding this. Others could add this if they would like to give it a go.
