### ISSUE TITLE
references returning undefined

### ISSUE THREAD

**Issue by barbalex** [mobxjs/mst-gql#229]
May be related to https://github.com/mobxjs/mst-gql/issues/223 and https://github.com/mobxjs/mst-gql/issues/92. May also be due to ignorance on my side.

I have two tables:
```graphql
type art {
  ae_id: uuid
  art_ae_art: ae_art
  (... a lot more relationships)
  changed: date
  changed_by: String
  id: ID!
  tsv: tsvector
}

type ae_art {
  ae_art_art: art
  id: ID
  name: String
  name_deutsch: String
  name_latein: String
}
```

When the app has loaded some data I can see there is an art with id `13121b40-9436-11ea-acf3-df093177d2de` because
```js
store.arts.get('13121b40-9436-11ea-acf3-df093177d2de')
```
returns:
```
ae_id: "ad0b1c83-6741-4937-b1e8-9d38c64460cd"
art_ae_art: undefined
changed: "2020-05-13"
changed_by: "alex@gabriel-software.ch"
id: "13121b40-9436-11ea-acf3-df093177d2de"
tsv: ""
__typename: "art"
```

Also I see that there is an ae_art with id `ad0b1c83-6741-4937-b1e8-9d38c64460cd` because
```js
store.ae_arts.get('ad0b1c83-6741-4937-b1e8-9d38c64460cd')
```
returns:
```
ae_art_art: undefined
id: "ad0b1c83-6741-4937-b1e8-9d38c64460cd"
name: "Alchemilla rubristipula"
name_deutsch: "Alchemilla rubristipula"
name_latein: "Alchemilla rubristipula"
__typename: "ae_art"
```

My question is: Why do the two models not return each other in the referencing fields: `art_ae_art` and `ae_art_art`?

I am happy to give any information missing above.

**Comment by chrisdrackett** [comment]
@barbalex what does the query look like when you get this data from the server?

**Comment by barbalex** [comment]
The query is:
```js
const { data } = useQuery((store) =>
  store.queryArt(
    {
      where: artFilter,
      order_by: { art_ae_art: { name: 'asc' } },
    },
    (d) => d.id.ae_id.art_ae_art((d) => d.id.name),
  ),
)
```

The result is:
```json
{
  "data": {
    "art": [
      {
        "__typename": "art",
        "id": "13121b40-9436-11ea-acf3-df093177d2de",
        "ae_id": "ad0b1c83-6741-4937-b1e8-9d38c64460cd",
        "art_ae_art": {
          "__typename": "ae_art",
          "id": "ad0b1c83-6741-4937-b1e8-9d38c64460cd",
          "name": "Alchemilla rubristipula"
        }
      }
    ]
  }
}

```

**Comment by barbalex** [comment]
Remember I mentioned:

> May also be due to ignorance on my side

Well, that was the reason. Some of my queries did not return __typename. Now that it is added, references are working!

Sorry for bugging you and thanks for great help!

**Comment by barbalex** [comment]
Hm. Since I diligently added __typename to all queries and fragments it seems that my hasura instance keeps crashing. There must be some more stuff I have to learn...

**Comment by chrisdrackett** [comment]
yep, for mst-gql to work currently you need an ID and __typename on everything that comes back from the server

**Comment by barbalex** [comment]
I have now added id's to all actual tables.

We are querying a few views though that analyze data change over time. It is not possible to have a real id here. So I guess I will have to prevent them from being processed by mst-gql by using the `--excludes` option when scaffolding.

And later query them using graphql-request directly. Or keep apollo just for that.

**Comment by barbalex** [comment]
Actually there is nothing preventing me from caching those views in mst itself, is there?
So I can probably query them using graphql-request and cache them manually in mst.

Until maybe one day it will be possible to tell mst-gql that the combination of an id with the date field is the primary key, I guess.
