### ISSUE TITLE
Enable numbers in string types

### ISSUE THREAD

**Issue by barbalex** [mobxjs/mst-gql#232]
Fields of postgres-type `text` and graphql type `String` are now built as:
```
types.union(types.undefined, types.null, types.string),
```

If a user enters a number into a field, for instance `2`, this error occurs:
```
expected Text, encountered Number: {"response":{"errors":[{"extensions":{"path":"$.variableValues.objects[0].nr","code":"parse-failed"},"message":"expected Text, encountered Number"}],"status":200},"request":{"query":"mutation insert_herkunft_rev($objects: [herkunft_rev_insert_input!]!, $on_conflict: herkunft_rev_on_conflict) { insert_herkunft_rev(objects: $objects, on_conflict: $on_conflict) {\n __typename\naffected_rows\n\n } }","variables":{"objects":[{"id":"12057320-946b-11ea-9ed2-b78ab786e87f","nr":2,"lokalname":null,"gemeinde":null,"kanton":null,"land":null,"bemerkungen":null,"changed":"2020-05-14","changed_by":"alex@gabriel-software.ch","_parent_rev":"2-1441a7909c087dbbe7ce59881b9df8b9","_depth":3,"_rev":"3-1441a7909c087dbbe7ce59881b9df8b9","_revisions":"{3-1441a7909c087dbbe7ce59881b9df8b9,2-1441a7909c087dbbe7ce59881b9df8b9,1-1441a7909c087dbbe7ce59881b9df8b9}"}],"on_conflict":{"constraint":"herkunft_rev_pkey","update_columns":["id"]}}}}
```
In this case my client wants the field to be named `nr` but also accept strings.

This is the reason why I personally define all text fields in mst like this:
```
types.union(types.undefined, types.null, types.string, types.number),
```

Would you consider adding the number type to text fields?

**Comment by chrisdrackett** [comment]
hm, I'm not entirely sure about this. Is there a problem with sanitizing the users input before sending it to graphQL?

**Comment by barbalex** [comment]
> Is there a problem with sanitizing the users input before sending it to graphQL?

No. Apart from it being often repeated code, so rather verbose. And easy to forget.

My main argument is: In the typed systems I personally know well (databases), accepting numbers in text fields is normal and expected behavior. And I would expect databases to be behind many uses of typed fields.

I do not know about TypeScript and mobx-state-tree though.

**Comment by chrisdrackett** [comment]
I think this is more a graphQL thing. Here is the spec on string:

http://spec.graphql.org/draft/#sec-String-Value

> Strings are sequences of characters wrapped in quotation marks (U+0022). (ex. "Hello World"). White space and other otherwise‐ignored characters are significant within a string value.

**Comment by barbalex** [comment]
Wouldn't that mean that "1" is also a string?

**Comment by barbalex** [comment]
I can pass 1 to Apollo as well as "1". This is why I was surprised of running in to new errors (I am converting from Apollo to mst.

**Comment by barbalex** [comment]
To be honest I am not sure if accepting numbers is a good decision. It just seemed like such a nuisance when converting

**Comment by chrisdrackett** [comment]
yeah, I can see that, but I think at the end of the day, at a base level, mst-gql should be true to the schema it is scaffold by. We can't be sure of how strict or not the graphQL server that is being used is so I think it's best to conform our types to the types defined by the graphQL spec wherever possible.
