### ISSUE TITLE
Allow configuration options for MSTGQL

### ISSUE THREAD

**Issue by Aryk** [mobxjs/mst-gql#242]
We should be able to configure this library with some basic options...here are two that come to mind that would be super useful...

1) regex or word match to exclude from Pimitives list. For example... I have the fields "computeUsersCount" and "computeExpensiveCount". It returns an INT but it's a rarely needed field that causes expensive calculations on the server (not just returning values). I should be able to say exclude /^compute/ from the auto-generated primitives list.

2) Defuault errorProc. There should be a default error handle when an error occurs with this library that you can configure once. Currently I have to do

```ts
const {error} = useQuery();
handleError(error)
```

In every component...

====

I'm sure there are atleast 2-3 more super useful things I'm not thinking of...

**Comment by chrisdrackett** [comment]
you could do this now by wrapping `useQuery` in your own hook that handles the errors and then use that throughout your project.

**Comment by Aryk** [comment]
That's a good point. I will look into doing it that way. I guess it seems excessive that if I want to just add a default error handler, I have to import useQuery not from the library itself. An added later of indirection for something that seems pretty standard, but it's just my cents.

:)
