### ISSUE TITLE
Enable enums to be used in queries

### ISSUE THREAD

**Issue by dpnolte** [mobxjs/mst-gql#25]
Currently, GraphQL Enum types are converted into MST's types.enumeration. However, there are still some open ends in supporting enums to use them in queries:
- Enums fields are not added to the ModelSelector/QueryBuilder of the containing model
  - probably require changes in `generateFragments` in generate.js
- Enums are not typed when being used as a query variable
  - probably require changes in `generateQueryBuilder` in generate.js

If anyone would be able to pick this up, great. Otherwise I might do this later.

**Comment by chrisdrackett** [comment]
@dpnolte can you confirm if this has been fixed in the recent changes? I think this can probably be closed, but I wanted to check with you first!

**Comment by chrisdrackett** [comment]
I'm going to close this for now, feel free to reopen if this is still an issue!
