### ISSUE TITLE
Scaffolding references unknown classes

### ISSUE THREAD

**Issue by impulse** [mobxjs/mst-gql#252]
Compile fails due to missing ModelSelectors and ModelTypes in `RootStore.base.ts`, specifically:

`StringModelSelector`
`StringModelType`
`BooleanModelSelector`
`BooleanModelType`

Example:

```ts
mutateLogout(variables?: {  }, resultSelector: string | ((qb: BooleanModelSelector) => BooleanModelSelector) = booleanModelPrimitives.toString(), optimisticUpdate?: () => void) {
  return self.mutate<{ logout: BooleanModelType}>(`mutation logout { logout {
    ${typeof resultSelector === "function" ? resultSelector(new BooleanModelSelector()).toString() : resultSelector}
  } }`, variables, optimisticUpdate)
}
```

> TypeScript error in /Users/lynx/Projects/mst-gql-test/src/models/RootStore.base.ts(115,67):
Cannot find name 'BooleanModelSelector'.  TS2304

> TypeScript error in /Users/lynx/Projects/mst-gql-test/src/models/RootStore.base.ts(115,92):
Cannot find name 'BooleanModelSelector'.  TS2304

**Comment by chrisdrackett** [comment]
can you give info about what you are scaffolding from?

**Comment by impulse** [comment]
> can you give info about what you are scaffolding from?

Example above has the following resolver (using [TypeGraphQL](https://typegraphql.com/docs/resolvers.html))
```
@Resolver()
export class LogoutResolver {
  @Mutation(() => Boolean)
  async logout(@Ctx() { res }: ServerContext): Promise<boolean> {
    sendRefreshToken(res, "");
    return true;
  }
}
```

**Comment by chrisdrackett** [comment]
sure, but what sort of graphql schema does this end up rendering out?

**Comment by impulse** [comment]
> sure, but what sort of graphql schema does this end up rendering out?
```ts
type Mutation {
  logout: Boolean!
}
```

**Comment by chrisdrackett** [comment]
Ok, this should be working if you are using `0.12.0`. We have something similar and this is what gets generated:

```
mutateUpsertCalendar(variables: { color?: string, id: string, title?: string, type?: CalendarType }, optimisticUpdate?: () => void) {
      return self.mutate<{ upsertCalendar: boolean }>(`mutation upsertCalendar($color: String, $id: ID!, $title: String, $type: CalendarType) { upsertCalendar(color: $color, id: $id, title: $title, type: $type) }`, variables, optimisticUpdate)
    },
```

from the following:

```
type Mutation {
    upsertCalendar(color: String, id: ID!, title: String, type: CalendarType): Boolean
}
```

If you can share a minimal reproduction it would be helpful! I'll try and find time to take a look regardless.

**Comment by impulse** [comment]
@chrisdrackett here is a reproduction for `0.12.0`: https://github.com/impulse/mst-gql-compile-bug 👍

**Comment by chrisdrackett** [comment]
I'm unable to get the server to run on this example (`Error: spawn nodemon ENOENT`). I ended up adding a test and a mutation to one of our examples here: https://github.com/mobxjs/mst-gql/commit/43870debc01920fa51af9c8d3013065da41cc167

maybe you can fork and get example1 into a breaking state? I feel like I must be missing something that is different between your code and mine, but so far it hasn't jumped out at me!

**Comment by impulse** [comment]
> I'm unable to get the server to run on this example (`Error: spawn nodemon ENOENT`)

Oh that might be because it was not added as dependency (sorry I had this installed globally). Alternatively you could just run `yarn build-ts` and `node dist/index.js`.


> maybe you can fork and get example1 into a breaking state? I feel like I must be missing something that is different between your code and mine, but so far it hasn't jumped out at me!

I'll try to on the weekend and report back 👍

**Comment by ivkirill** [comment]
I have the same issue with interface defined in schema:

```
type Query {
    available(input: AvailableInput): [Element!]
}
input AvailableInput {
    elementID: ID!
}

interface Element {
    payload: Payload!
}

type FixedElement implements Element {
    payload: Payload!
    value: String!
}

type NumberElement implements Element {
    payload: Payload!
    amount: String!
}

type Payload {
    value: ID!
}
```

**Comment by chrisdrackett** [comment]
@ivkirill I haven't used interfaces myself so I can't comment on how well mst-gql handles them. If you are running into an issue I think it would be best to open a new issue specific to interfaces.

**Comment by Oba-One** [comment]
@impulse @chrisdrackett I see the type error in 0.12 but not in 0.11 or below for more context.

**Comment by chrisdrackett** [comment]
If someone can send a working reproduction I am happy to take another look!

**Comment by Oba-One** [comment]
@chrisdrackett I invited you to my repo where I'm experiencing the issue. Let me know if you need more details?

**Comment by chrisdrackett** [comment]
@Oba-One I don't see mst-gql in here?

**Comment by Oba-One** [comment]
@chrisdrackett Sorry forgot to push up my work. Everything is up now with a small readme

**Comment by finkef** [comment]
It seems that this only happens for required Scalar Types. Ran into this issue as well with `mutation { foo: String! }`, it references `StringModelSelector` which doesn't exist. With `mutation { foo: String }` it correctly just uses `string`.

**Comment by beepsoft** [comment]
A just ran into this issue as well. Created a test case for it:

https://github.com/beepsoft/mst-gql/tree/bugs/issue-252

Run `yarn test` and it will fail at the `"scaffolding with scalar type"` test.

I think the solution would be not to generate selectors for queries returning scalar types, but I'm not familiar with this part of the generator yet.

**Comment by beepsoft** [comment]
The problem seems to be here:

https://github.com/mobxjs/mst-gql/blob/926d8a7fb512376b969301a55e2e42d5a96dde49/generator/generate.js#L811

This is not evaluated to `true`, therefore later we generate a full object selector instead of just the name of the field.

Ie.

```js
    queryHelloWithString(variables?: {  }, resultSelector: string | ((qb: StringModelSelector) => StringModelSelector) = stringModelPrimitives.toString(), options: QueryOptions = {}) {
      return self.query<{ helloWithString: StringModelType}>(\`query helloWithString { helloWithString {
        \${typeof resultSelector === \\"function\\" ? resultSelector(new StringModelSelector()).toString() : resultSelector}
      } }\`, variables, options)
    }
```

instead of

```js
	queryHelloWithString(variables?: {  }, options: QueryOptions = {}) {
	    +       return self.query<{ helloWithString: string }>(`query helloWithString { helloWithString }`, variables, options)
	
```
For my test case the GraphQL type that is being checked looks like this
```
        [Object: null prototype] {
          kind: 'NON_NULL',
          name: null,
          ofType: [Object: null prototype] {
            kind: 'SCALAR',
            name: 'String',
            ofType: null
          },
          origName: null
        }
```

This change seems to fix it:

```js
    const isScalar = type.kind === "SCALAR" || type.ofType?.kind === "SCALAR"
```

**Comment by beepsoft** [comment]
@chrisdrackett Should I create a PR with the fix above?

**Comment by Oba-One** [comment]
Awesome!

**Comment by chrisdrackett** [comment]
@beepsoft please do if you have time! Things have been insane for me with school starting and work so I just haven't had many free cycles 😭

**Comment by beepsoft** [comment]
@chrisdrackett I feel you 😀 Here's the PR: https://github.com/mobxjs/mst-gql/pull/277

**Comment by beepsoft** [comment]
@chrisdrackett Could you please merge this fix if you  have the time. This bug is kind of a  blocker for me right now.

**Comment by chrisdrackett** [comment]
@chrisdrackett on it right now, sorry for the delay!

**Comment by beepsoft** [comment]
@chrisdrackett Thanks, 0.13.0 works all right for me!  The issue can be closed, I think.
