### ISSUE TITLE
Interfaces from graphql schema not generated into models, but used in rootStore actions

### ISSUE THREAD

**Issue by ivkirill** [mobxjs/mst-gql#256]
I have a schema with interface:

```
type Query {
    available(input: AvailableInput): [Element!]
}
input AvailableInput {
    elementID: ID!
}

interface Element {
    payload: Payload!
}

type FixedElement implements Element {
    payload: Payload!
    value: String!
}

type NumberElement implements Element {
    payload: Payload!
    amount: String!
}

type Payload {
    value: ID!
}
```

After generating I have an error in rootStore.base.ts with using `ElementModelType` but its not exists.

Repo with error reproduction: [https://github.com/ivkirill/mst-gql-interface ](url)

**Comment by special-character** [comment]
I think this is potentially related to #255. The function that is generating unions and interfaces is the same and I had the same issue with unions.

**Comment by special-character** [comment]
Just started running into this in my own app. I think that it will be very similar to this PR that I solved this for unions: https://github.com/mobxjs/mst-gql/pull/257
