### ISSUE TITLE
Examples with classes vs hooks

### ISSUE THREAD

**Issue by dgdosen** [mobxjs/mst-gql#26]
Are there any examples that use classes? (and decorators?) vs hooks? Is that possible?  I'm looking to take baby steps...

**Comment by dpnolte** [comment]
The simplest example is example 1, but hooks are being used. Maybe you can start from example 1 and try to convert the [home component](https://github.com/mobxjs/mst-gql/blob/master/examples/1-getting-started/src/app/Home.tsx) to a class with decorators as a first step?

**Comment by mweststrate** [comment]
Yes, it should be no problem to use it without hooks, if you follow for example the following pattern:

For case, see:

```typescript
@observer // don't forget!
class MyClass extends React.Component {
  static contextType = StoreContext; // Imported from the generated react.ts

  constructor() {
    super()
    // this.context will be the store (could also use StoreContext.Consumer to obtain that in render)
    this.state = { query: this.context.fetchStuff() }
  }

  render() {
    // The query has all the different states, .case is a convenience way to switch over the different states
    return this.state.query.case({
       loading: () => <Loading />,
       error: (e) => <p>Not ok {e}<p>,
       data: (todos) => <ul>{todos.map(....)}</ul>,
    })
  }
}
```

**Comment by fullofcaffeine** [comment]
Most of my components are class based, so I'm trying to use the context approach. The example shown here is not working well for me, `this.context`  returns undefined if called from the constructor.

If called from the ` render`  function, the it seems to work, but TypeScript doesn't seem to be aware its type, it's currently typed as `any`. Do you know why?

Any insights appreciated.

**Comment by fullofcaffeine** [comment]
Ok, I figured it out!

For anyone else using `mst-gql` with React class components and TypeScript, check out this issue: https://github.com/mobxjs/mst-gql/issues/132. 

The example from @mweststrate works fine for vanilla ES6, but if you're using TypeScript, you won't get the proper typed context. Just be sure to add the additional line I mention in that issue.

**Comment by fullofcaffeine** [comment]
Another thing: 

To actually access the `context` from the constructor function, I had to do the following:

```typescript
 constructor(props, context) {
    super(props, context)
    this.state = { query: context.fetchStuff() }
  }
```

So, I had to actually add the parameter to the constructor and use it instead of accessing it from `this`. Hope this helps anyone out there that went through a similar issue when trying to run this example.

**Comment by mweststrate** [comment]
I think that is the normal React behavior indeed

**Comment by fullofcaffeine** [comment]
@mweststrate I have a related question: what is the proper way to ignore one of the callbacks, say, if I only want to define the `data` callback and leave `loading` and `error` undefined?

**Comment by fullofcaffeine** [comment]
Ah, nevermind, I see the query method already returns it in `data`.
