### ISSUE TITLE
Interface and Union .ofTypes error

### ISSUE THREAD

**Issue by roshanreacts** [mobxjs/mst-gql#263]
Hello Dev,

I'm using this product in couple of my developments. Great tool 👍.

Well I ran into following error recently while scaffolding a Union Type.

```
.\node_modules\mst-gql\generator\generate.js:503
      const mstUnionArgs = interfaceOrUnionType.ofTypes.map(t => {
                                                ^

TypeError: Cannot read property 'ofTypes' of undefined
    at handleInterfaceOrUnionFieldType (.\node_modules\mst-gql\generator\generate.js:503:49)
    at handleFieldType (.\node_modules\mst-gql\generator\generate.js:458:25)
    at handleField (.\node_modules\mst-gql\generator\generate.js:407:34)
Compiled with warnings.
```

I tried to look into the issue, then I found a bug with name conventions for union types. `type.names` are converted but while getting the union types it is comparing `possibleTypes.name` which is not processed with naming convention. Which results into following issue.

So I have fixed it and added a pull request, review the changes and add it into further releases.

Thanks

**Comment by special-character** [comment]
@roshanreacts Thanks for creating the issue, can you give us an example of your schema that failed the scaffold step?

I helped write some of the union generating code and might be able to help. Did you have a PR we could look at? I didn't find one but thought you meant you had submitted one.
