### ISSUE TITLE
updating the store outside of graphql

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mst-gql#27]
I'm looking into using mst-gql on a project I'm working on. I'm really happy so far with the models, queries and mutations!

That being said I'm currently stuck around have live data updates. Our server is currently serverless so we don't currently use GraphQL subscriptions. What we do currently is use pusher to send data from the server to the client and then the client updates the Apollo cache.

What I'm curious about is if something similar is possible in this library. i.e. can I update the local store based on an event from pusher or similar?

**Comment by chrisdrackett** [comment]
I wonder if `merge` is what I'm looking for. I'll play with it a bit!

**Comment by dpnolte** [comment]
Yes, that sounds right to me. When subscribed to your event, you could use `merge` to merge the incoming data from pusher with the store. But it is important that the data still contain `__typename` and - if possible - any `id` to upsert the correct model. You can review the implementation logic here: https://github.com/mobxjs/mst-gql/blob/master/src/mergeHelper.ts
Alternatively, you could implement your own merge logic or you could use `applySnapshot` if you want to completely update a model (can be any node in the tree).

**Comment by flybayer** [comment]
Just be aware that `merge` won't removed deleted records from your store! You may or may not care about this depending on your app.

**Comment by chrisdrackett** [comment]
yeah, luckily (currently at least) we're using a boolean for deleted items so that should not be a problem. Thanks!

**Comment by chrisdrackett** [comment]
working like a charm, I'm going to close this issue!

**Comment by chrisdrackett** [comment]
I'm going to reopen this as I'm running into a new issue. I've found that by using merge my lifecycle events (`afterAttach`) don't seem to be firing. Is this to be expected? If so, I'm wondering if there are other ways I might update items outside of GraphQL?

The issue I'm running into is a `User` has `Items` and each item has an `owner` that is a `User`. When an updated `Item` comes in from pusher I want to add it to the store and also update the related `User`s item list. I was hoping to do this via lifecycle hooks but have found they don't fire as far as I can tell when using merge.
