### ISSUE TITLE
INPUT_OBJECT in typescript

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mst-gql#28]
I tried to use mst-gql with a Prisma generated schema today and ran into the following error:

```
Error: Not implemented printTsType yet, PR welcome for {
  "kind": "INPUT_OBJECT",
  "name": "ItemWhereUniqueInput",
  "ofType": null
}
```

when looking at my schema I see:

```
input ItemWhereUniqueInput {
  id: ID
}
```

**Comment by mweststrate** [comment]
Input object types have not been implemented yet, but it should be trivial to do so, as they don't need a corresponding MST type, only a typescript interface (the logic is already partially present in the generator). Alternatively, it could be put to `any` atm.

**Comment by elie222** [comment]
I've made a PR that puts it to `any` and logs a warning. Will look to implement it properly now.

**Comment by dpnolte** [comment]
@chrisdrackett could you check if #36 works for your use case? Thanks!!

**Comment by chrisdrackett** [comment]
@dpnolte yep! looks like I can now generate using typescript without issue! 🎉
