### ISSUE TITLE
Loading always returns true

### ISSUE THREAD

**Issue by mhaagens** [mobxjs/mst-gql#295]
I'm using Next.js with mst-gql.
I have a simple page (/users) that fetches data, but it always returns `loading === true` unless I go to another page (/someotherpage) and come back. Only then is the component populated with data. I'm wrapping everything in `observer`. It also works fine if I load the page on the server, the data is correctly rendered on the client.

```
const UsersPage = observer(() => {
  const { data, error, loading } = useQuery((store) => store.queryUsers());

  if (error) return <div>{error.message}</div>;
  if (loading) return <div>Loading...</div>;

  return (
    <>
      <UsersList users={data.users} />
    </>
  );
});
```

**Comment by iswara108** [comment]
@mhaagens Sounds like a question for the forum on https://spectrum.chat/mst-gql?tab=posts.
Can you please send something that reproduces the problem? A minimalist version on codesandbox or a github link would do.

**Comment by mhaagens** [comment]
I downgraded mobx, mobx-react and mobx-state-tree and everything started working, so it looks like there's an issue somewhere with the other MobX dependencies.
I downgraded from:
```
"mobx": "^6.0.4",
"mobx-react": "^7.0.5",
"mobx-state-tree": "^4.0.2",
"mst-gql": "latest",
```
to 
```
"mobx": "^5.15.7",
"mobx-react": "^6.3.1",
"mobx-state-tree": "^3.17.3",
"mst-gql": "latest",
```

**Comment by mattiasewers** [comment]
@mhaagens yeah it does not support mobx 6 yet
