### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by elie222** [mobxjs/mst-gql#3]
Some issues running examples. I've tried:

```sh
yarn
yarn prepare-examples
```

But get this error:
> "./mst-gql1557842644.tgz": Tarball is not in network and can not be located in cache

I don't understand why this is a dependency in the `package.json` either:

```json
"mst-gql": "file:./mst-gql1557842644.tgz",
```

**Comment by mweststrate** [comment]
This problem should be fixed now! 
Run `yarn && yarn build` in the root first, and after that, `yarn` in any of the examples should work. 

Feel free to close the issue if that is indeed the case :)
