### ISSUE TITLE
Looking for maintainers!

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mst-gql#302]
Within the last 6 months we've been moving away from using `mst-gql` in our project and as a result I've been spending less and less time maintaining this project. While I'm not the sole maintainer, I have been doing a good amount of the work around preparing and doing releases, which clearly has fallen off its normal pace.

Hopefully either an existing maintainer or someone new is able to step up and manage releases. I'm happy to support in the transition as much as possible!

**Comment by mattiasewers** [comment]
@chrisdrackett Hi, why did you move away from it and what are you using instead?

**Comment by rdewolff** [comment]
Sorry to read this. That's the kind of issue I don't like to read when considering to use mst-gql for our saas app.

Could you please elaborate a bit more on:

> We want our app to have great offline support and there are just too many little issues with our current approach.

That'd help the community :)

**Comment by beepsoft** [comment]
@chrisdrackett I'm not really familiar with the npm publishing workflow yet, but I worked a bit on mst-gql before and I would like to see the project develop and succeed. I use it in a number of react SPA and react-native apps, so I would be glad to help with the maintenance if someone could join me in this.

**Comment by beepsoft** [comment]
@chrisdrackett did you succeed finding a maintainer? I've seen @jesse-savary merged a PR recently. Will he manage further developments? I'm really looking forward to #294 and #303 be merged.

**Comment by jesse-savary** [comment]
@beepsoft will deal with these today; `mst-gql` is very important to my company/project and I'm behind it full-force.

I apologize for not paying better attention to the open PRs. Please feel free to tag me or assign me where needed. Let's get this train moving 😄

**Comment by beepsoft** [comment]
@jesse-savary it is really good news, thanks for your work! 😃 I'm also very much invested into `mst-gql` so I hope it will get better and better.

**Comment by chrisdrackett** [comment]
Thanks so much @jesse-savary! let me know if you need anything from me or have any questions!

**Comment by jesse-savary** [comment]
My current goal is to get every (valid) PR merged in and to take care of any small issues. @chrisdrackett I will likely ping you to sort out releases + ensure I don't blow up NPM; expect to hear from me sometime in the next week or two :)

**Comment by chrisdrackett** [comment]
sounds good!

**Comment by mylifenp** [comment]
I have been trying mst-gql from few months now. I find it really fascinating. I am still probably a noob,  but would really love to help the project grow. Is there anything i can do?

**Comment by beepsoft** [comment]
@jesse-savary could you proceed with the PR-s? Do you plan to publish a new release?

**Comment by jesse-savary** [comment]
> @jesse-savary could you proceed with the PR-s? Do you plan to publish a new release?

Hey @beepsoft, the nature of "generate and forget about your models" makes it tough for my scatterbrain to remember to check in here :facepalm: 

@chrisdrackett I'm going to review/merge the remaining PRs tomorrow -- how do we go about releasing afterward?

**Comment by jesse-savary** [comment]
PRs have been merged, just need to know what I have to do cut a new release.

**Comment by chrisdrackett** [comment]
@jesse-savary can you give me your npm username and I can add you to the project

**Comment by chrisdrackett** [comment]
@jesse-savary the process I generally take is:

1. test locally
2. build the package `yarn build`
3. update `CHANGELOG.md`
4. release the new version to npm `yarn publish`
5. send the created tag to GitHub and add the same notes from changeling to the GitHub release (https://github.com/mobxjs/mst-gql/releases)
6. 💰

**Comment by richierob62** [comment]
@chrisdrackett  @jesse-savary  Hey guys, thank you for all you do.  Do you have a feel for when you'll have the release with the fix for #306 out? I'm very aware that you all have other obligations...

**Comment by chrisdrackett** [comment]
I can see if I can fit it in this week, but because we're not longer using mst-gql its a bit harder for me to test "real world". I'd love to give @jesse-savary or similar npm access so someone else can manage releases :)

**Comment by richierob62** [comment]
> I can see if I can fit it in this week, but because we're not longer using mst-gql its a bit harder for me to test "real world". I'd love to give @jesse-savary or similar npm access so someone else can manage releases :)

@chrisdrackett How are you guys generating your mst models now that you're not using mst-gql?  I shudder at the thought of doing them manually.  Or, a related request, could you give me some guidance on using mst-gql to generate the models only?  In my mind, that the time-consuming part of the process I'm hoping to avoid.

**Comment by jesse-savary** [comment]
@chrisdrackett created a new account https://www.npmjs.com/~jesse-savary and read over your release process. Will get some kind of alpha out the door as soon as I have access.

**Comment by chrisdrackett** [comment]
@jesse-savary ok! added you to the project, you should be able to release now!

**Comment by jesse-savary** [comment]
@chrisdrackett thank you! I'll get something out ASAP!

**Comment by jesse-savary** [comment]
0.14.0 has been cut :)
