### ISSUE TITLE
GraphQL union type fields aren't created as references

### ISSUE THREAD

**Issue by techknowfile** [mobxjs/mst-gql#304]
If a model contains a Union type object, we end up with
`types.union(types.late(() => AreaModel), types.late(() => ScheduleModel))`

when it should actually be
`MSTGQLRef(types.union(types.late(() => AreaModel), types.late(() => ScheduleModel)))`

Because it's not creating it as a reference, it will fail to load the snapshot, as it will try to create a duplicate object of the Union'd type instead of referencing the existing object in the RootStore map.

I'm guessing this is may be because only roots are turned into MSTGQLRef's elsewhere, and union types of course not being turned into roots

**Comment by emckay** [comment]
Here is a reproduction of this issue: https://github.com/mobxjs/mst-gql/commit/8d599bf85af64dafc9f5a853c75f9a05a561c78d

and a workaround: https://github.com/mobxjs/mst-gql/commit/88b75044fbf03fefc6370e783cb7dcbf1b1d014b

happy to help fix this with a little guidance

**Comment by giaset** [comment]
Hey all, any updates on this? This is still an issue in late December 2021. We're working around it by doing this:

`games: types.union(types.undefined, types.array(types.union(MSTGQLRef(types.late((): any => BaseballGameModel)), MSTGQLRef(types.late((): any => BasketballGameModel)), MSTGQLRef(types.late((): any => FootballGameModel)), MSTGQLRef(types.late((): any => GolfGameModel)))))`

Also interesting, if we don't add the `: any` to our arrow functions, it breaks typing for the entire model. We get an error about the model being referenced directly or indirectly in its own initializer...
