### ISSUE TITLE
useQuery {loading} doesn't re-render when query complete (Latest versions)

### ISSUE THREAD

**Issue by techknowfile** [mobxjs/mst-gql#306]
The useQuery hook does not result in a re-render when { loading } from the underlying query changes from true to false.  This issue doesn't occur with older versions.

mobx 6.0.4
mobx-react 7.0.5
mobx-state-tree 5.0.0
mst-gql 0.13.0
react 17.0.1
react-dom 17.0.1
react-scripts 4.0.0

[Spectrum Post](https://spectrum.chat/mst-gql/general/usequery-loading-doesnt-re-render-when-query-complete-latest-versions~a543d84d-ce8c-4091-9e01-3598daa97ee9)

https://codesandbox.io/embed/youthful-oskar-5v1wn?file=/src/RocketsContainer.js

As you can see in the codesandbox, the query completes successfully, but the component doesn't re-render. You can run `values(store.rockets)` in console to see that the query has completed successfully (and you can see it in the log from the query.then() callback).

If you were to then change a value in the `RocketsContainer` file to make the component re-render (like, for example, add a "g" to "loadingg"), the component re-renders with the names of the rockets.

If I downgrade mobx, mobx-state-tree, and mobx-react, the component updates properly, but then other observables stop re-rendering. I'm unable to replicate the issue of other observables no longer re-rendering in codesandbox. What's strange is that they work find in my old project, but don't in my new one, even when I replicate all dependencies exactly.:
https://codesandbox.io/embed/gracious-stonebraker-jc4ig

**Comment by BradenM** [comment]
@techknowfile, was running into the same issue. Resolved it by upgrading mst-gql to mobx 6. See my PR: #294

**Comment by techknowfile** [comment]
@BradenM that's great news. Trying to test your branch out by installing through yarn, it doesn't seem to find mst-gql as an importable package

**Comment by BradenM** [comment]
@techknowfile Weird. Personally, I actually just apply the changes using [patch-package](https://www.npmjs.com/package/patch-package), but I'll try and install it from git to see if I can find what's up with it.

**Comment by beepsoft** [comment]
@techknowfile you may try my package with PR #294 merged into master (created using gitpkg):

    "mst-gql": "https://github.com/beepsoft/mst-gql#mst-gql-v0.13.0-mobx6-support-gitpkg",

**Comment by techknowfile** [comment]
@BradenM I tried MST 5.0.1 and the issue still remains (can test it in the same code sandbox above!)

**Comment by mcarcaso** [comment]
> @techknowfile you may try my package with PR #294 merged into master (created using gitpkg):
> 
> ```
> "mst-gql": "https://github.com/beepsoft/mst-gql#mst-gql-v0.13.0-mobx6-support-gitpkg",
> ```

This worked for me! Thank you @BradenM for making that PR and @beepsoft for sharing that package. Do we know when we can expect a new release of mst-gql to get cut?

**Comment by beepsoft** [comment]
@jesse-savary is working on the new release, see #302

**Comment by jesse-savary** [comment]
@techknowfile Hey, could you give `0.14.0` a try? :)

**Comment by techknowfile** [comment]
@jesse-savary that fixed it. Thank you!
