### ISSUE TITLE
Pagination With Subscriptions

### ISSUE THREAD

**Issue by hazemturki** [mobxjs/mst-gql#316]
Not sure if this is best place to discuss this, but my problem goes as follows;
I am using mst-gql to manage all data from my GraphQL server and 

My problem is that am trying to list a big number of objects that won't fit in a single request, so I will be forced to apply some type of **pagination** to handle that, a simple cursor or pagesize+pagenumber solution was very easy to implement. But afterwards I wanted to tackle a more complicated issue where I want to be able to **subscribe** for changes such as a deletion/creation/update of one of these objects and have them update in realtime.

Is this possible with mst-gql? If yes, I would appreciate any guidance or a simple GraphQL schema that supports that.

**Comment by Aryk** [comment]
I've been developing this for over a year...I don't use specifically for subscriptions, but I have used for appending new data that comes from subscriptions. Haven't had time to abstract this into a library, but maybe you can find it useful:

https://github.com/mobxjs/mst-gql/issues/211#issuecomment-803496145

**Comment by Benz19** [comment]
Hi @hazemturki Im reviewing all the open issues in an attempt to clean things up.  Are you still having issues?

**Comment by hazemturki** [comment]
Had to switch to another solution. Will close the issue.
