### ISSUE TITLE
`realpath` missing when running examples

### ISSUE THREAD

**Issue by elie222** [mobxjs/mst-gql#32]
When running the examples I ran into this issue when running `yarn install`:

```sh
../../scripts/install-mst-gql.sh: line 6: realpath: command not found
```

Doing this fixed it for me:

```sh
npm install --global realpath
```

`realpath-native` does get installed in the root `node_modules` folder. Should the example bash script be updated to rely on the copy of `realpath` in `node_modules`?

**Comment by mweststrate** [comment]
It is a built-in linux utility, probably not available on Mac.... It is just to make the path absolute in the build script, probably there is a mac compatible alternative, as it is quite a basic shell feature :P

**Comment by elie222** [comment]
Added a note to the README about it:
https://github.com/mobxjs/mst-gql/commit/4ebc07e04f124142d34b3570e04609cf824d4a60

Closing for now.
