### ISSUE TITLE
What is the name of this pattern where all the data is parsed into a flattened root store and turned into references

### ISSUE THREAD

**Issue by techknowfile** [mobxjs/mst-gql#327]
Sorry that this is a question and not an issue, but with spectrum dead I don't know where else to ask.

I'm moving away from mst-gql to pure MobX, but I want to recreate the pattern of making query requests from the root store and then parsing the response data into flat maps and a reference tree.

Is there a name for this pattern?

**Comment by iswara108** [comment]
Normalization

**Comment by techknowfile** [comment]
@iswara108 Thank you! I just replicated the merge() function for my less-fancy mobx data store implementation, so so cool. I know of normalization from a database perspective, but can't seem to immediately find any examples of it being used for something like this (a data store derived from JSON).  Would love other examples of this being done in the wild if you happen to know of any so I can dig in a little deeper.

**Comment by iswara108** [comment]
I think this can be a good reference material, or at least something to get ideas from.
https://github.com/paularmstrong/normalizr
@techknowfile
