### ISSUE TITLE
Support for operationName

### ISSUE THREAD

**Issue by antondomratchev** [mobxjs/mst-gql#352]
Hello everyone and Happy forthcoming New Year!

Firstly I would like to thank everyone who've contributed to this project! It's been really awesome to see continued support of this project for so long.

We've been using MST since the very early days and continue to enjoy using this library in our projects. I've recently started looking into improving our GraphQL server performance and noticed that out applications (specifically ones using MST-GQL) were not properly categorized in our server side APM service. Several hours turned into days of investigation has revealed that in order for the GraphQL requests to be properly categorized we needed to use operationNames. This was not a big deal since most of out queries were documented and written with operationNames. After further investigation and source sifting, I've found 
 that mst-gql does not send an operationName with the request for a couple of reasons.
 1. mst-gql relies on graphql-request to prepare and send the actual fetch request. This is fine because the support for operationName was recently added to graphql-request ^3.5.0
 2. When monkey patch the latest version of `graphql-request` the second reason becomes apparent. `graphql-request` can only extract operationName when the query is being passed as DocumentNode type defined in `graphql` module since its easy to parse out the operationName using the AST.
 
 At this point I am questioning where can this operationName be handled? I've been looking through the Query implementation and I am not sure why its necessary to convert the query propery into string https://github.com/mobxjs/mst-gql/blob/9b9a512b92fb2c909be90bb59bf4dda3023baba4/src/Query.ts#L50? A few guesses I have might be for `queryKey` which is used for caching and for `QueryBuilder` module. It's also possible that at the time this was written, graphql-request only supported string query when calling `request` and `rawRequest`. 
 
I want to see if anyone had any input on this discussion as well as any feedback about introducing support for operationName (maybe I missed a simple way of achieving this that already exists).

**Comment by Benz19** [comment]
hey @antondomratchev I'm helping @jesse-savary review all the issues in an attempt to get everything cleaned up.  I noticed this has been silent for awhile.  Do you still have questions I can help with?
