### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by elie222** [mobxjs/mst-gql#4]
Is query batching currently supported?

Seems like you could often end up making multiple requests. I believe Apollo Client has this functionality built-in.

If not supported, is this a good feature to be added to the library, or you'd recommend users handle larger queries in a different way?

**Comment by mweststrate** [comment]
I'm not familiar with that appollo client feature, let's see if more people need it :) In that case it could be added, or we could investigate if we could reause that feature from apollo-cient (see also #10 )

**Comment by elie222** [comment]
May not be too important at this stage. Good blog post on it and it’s
drawbacks:

https://gist.github.com/3aa404dbd5953bf29c3f8d2962c845fa

It isn’t enabled by default in Apollo.

**Comment by mweststrate** [comment]
Ok, I'll close it for now. Can always reopen later.
