### ISSUE TITLE
Is it possible to have local-only queries/mutations?

### ISSUE THREAD

**Issue by traviswimer** [mobxjs/mst-gql#406]
I'm looking into switching to this `mst-gql` from `@apollo/client`, but I am currently using Apollo's ["Local-only Fields"](https://www.apollographql.com/docs/react/local-state/managing-state-with-field-policies/) to store certain data.

In other words, I have some temporary data that never needs to be sent/received from the server-side, but it also needs to persist when components un-mount or the app is closed.

I haven't been able to find any mention of this type of functionality in the documentation. Is `mst-gql` and it's cache capable of handling this use-case?

**Comment by beepsoft** [comment]
`mst-gql` uses [Mobx State Tree](https://mobx-state-tree.js.org/) under the hood, which is actually the "cache" where `mst-gql` stores graphql results and it can be used to store any other values either next to you graphql entities or anywhere else in the mst tree.

`mst-gql` generates 2 files for each of your graphql types:
- `SomeGraphqlTypeModel.ts` and
- `SomeGraphqlTypeModel.base.ts` and

`SomeGraphqlTypeModel.base.ts` is the base model mapping all fields of the `SomeGraphqlType` and it is extended by `SomeGraphqlType.ts` where you can define your own value to be stored along with any instance of `SomeGraphqlTypeModel`.

For example, you can do this to add `myLocalStringValue` to your `SomeGraphqlTypeModel`:

```ts
/**
 * SomeGraphqlTypeModel
 */
export const SomeGraphqlTypeModel = SomeGraphqlTypeModelBase
  .props({
    myLocalStringValue: types.string
  })
  .actions(self => ({
    setMyLocalStringValue(val: string) {
      self.myLocalStringValue = val
    },
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
}))
```

Hope this helps!

**Comment by traviswimer** [comment]
@beepsoft Thanks for the explanation. This definitely helped a lot.

Digging a little deeper into this, I actually need an entire `Model` on my store to be local, so I ended up with something like this in my `RootStore`:

```typescript
export const RootStore = RootStoreBase.props({
	myLocalData: types.model("MyLocalData", {
		myLocalStringValue: types.string
	}),
}).actions((self) => ({
	setMyLocalStringValue(val: string) {
		self.myLocalData.myLocalStringValue = val
	},
	// This is an auto-generated example action.
	log() {
		console.log(JSON.stringify(self));
	},
}));
```

I think in my case `types.model` may be fine, but is is any reason I should be using `ModelBase` instead?

It's unclear to me what makes sense when I don't intend to be making any GQL api requests for this model. Is it generally safe to assume that anything local like this should be using `mobx-state-tree` rather than anything provided by `mst-gql`?

Thanks again for your help!

**Comment by beepsoft** [comment]
The `RootStore` generated by `mst-gql` works just like any other MST model, so you can extend and combine it with other stores (models) as you like and your models don't need to extend `mst-gql`'s `ModelBase`.

What you described is totally valid, however it is also possible to have a top level store the `mst-gql` `RootStore` is a part of. For example, I usually have this kind of MST store layout in my apps: I have an `AppStore`, which contains a `gqlStore`, a `globals` model and models for my pages:

```ts
import { RootStore } from './models'
import { createHttpClient } from "mst-gql";
import { createClient } from 'graphql-ws';
import { createContext, useContext } from "react";

const GlobalsModel = types.model('GlobalsModel', {
	jwt: types.union(types.undefined, types.maybeNull(types.string)),
	language: types.optional(types.string, "en")
})
.action(self => {
	// ...
})
	
const Page1Model = types.model('Page1Model', {
	// props
})
.actions(self => {
	// actions
})

const Page2Model = types.model('Page2Model', {
	// props
})
.actions(self => {
	// actions
})

const AppStore = types.model('AppStore', {
    gqlStore: types.late(() => RootStore),
    globals: types.optional(GlobalsModel, {}),
    page1Model: types.optional(Page1Model, {}),
    page2Model: types.optional(Page2Model, {}),
}).actions(self => {
	// actions
})

const gqlHttpClient = createHttpClient(...)

const gqlWsClient = createClient(...)

const mstEnv = {
    gqlHttpClient,
    gqlWsClient
}

const appStore = AppStore.create(
    {
        gqlStore: GqlRootStoreBase.create(
            {
                language: args.defaultLanguage,
                defaultLanguage: args.defaultLanguage
            },
            mstEnv
        ),
        globals: {
            jwt: null,
            language: args.defaultLanguage
        },
       page1Model:{/*... init model ...*/},
       page2Model:{/*... init model ...*/},
    },
    mstEnv
)

export const AppStoreContext = createContext(appStore);

// Hook to access the appStore anywhere
export function useAppStore() {
  const store = useContext(AppStoreContext);
  if (!store) {
    throw new Error(
      "useAppStore() can only be used inside the AppStoreContext provider"
    );
  }
  return store;
}
```


Then I have this App component:

```ts
import { appStore, AppStoreContext } from "./store";

const App = () => {
  return (
        <AppStoreContext.Provider value={appStore}>
			...
        </AppStoreContext.Provider>
  );
};
```

And in my components I can access my AppStore like this:

```ts
import { observer } from "mobx-react";
import { useAppStore } from "./store";

export function SomeComponent = observer(props = {

    const appStore = useAppStore();

	return (
		<div>{appStore.globals.language}</div>
	)
})
```

**Comment by traviswimer** [comment]
@beepsoft Thanks for the example code! That seems like a far more organized way to manage things than how I was trying to do it.

I've struggled a little with wrapping my head around everything because I'm basically trying to learn `mobx`, `mobx-state-tree`, and `mst-gql` all at the same time. I think the documentation for `mst-gql` is probably written from the perspective that you'll already be familiar with how everything else with MobX works.

My perspective is a little different. I found `mst-gql` because I was looking for an alternative to Apollo, and so far it seems to be a good fit for that. But, I'm finding that I need to become more familiar with the other MobX dependencies to use it effectively.

My point being, do you think it would be worthwhile to add documentation about managing local data or is it safe to assume most people will be familiar enough with MobX state tree that it's unnecessary?

Either way, you answered my questions, so I'm going to close this issue.
