### ISSUE TITLE
curious what to do with datetime or similar

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mst-gql#44]
I have a scalar `DateTime` that I'd love to teach mst-gql to treat as a Date.

So far I've tried editing my `models/<item>Model.ts` to have:

```
export const ItemModel = ItemModelBase.props({
  createdAt: types.maybe(types.Date),
})
```

and that much seems to be working, however I'm not sure where to put the code that takes the string returned from the server and transforms it into a Date.

**Comment by chrisdrackett** [comment]
Nevermind, I was able to figure this out. If anyone else is curious to support (for example) Luxon dates you can use the following in `models/<item>Model.ts`:

```
import { types } from 'mobx-state-tree'
import { DateTime } from 'luxon'

export const Luxon = types.custom<string, DateTime>({
  name: 'Luxon',
  fromSnapshot(value: string) {
    return DateTime.fromISO(value)
  },
  toSnapshot(value: DateTime) {
    return value.toISO()
  },
  isTargetType(value: string | DateTime): boolean {
    return value instanceof DateTime
  },
  getValidationMessage(value: string): string {
    if (
      /\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d(\.\d+([+-][0-2]\d:[0-5]\d|Z))?/.test(
        value,
      )
    ) {
      return ''
    }
    return `'${value}' doesn't look like 'YYYY-MM-DDTHH:mm:ss.SSSZ'`
  },
})


export const ItemModel = ItemModelBase.props({
  createdAt: types.maybe(Luxon),
})
```

**Comment by Aryk** [comment]
hey @chrisdrackett are you replacing "createdAt" prop? I didn't know that was possible, but it makes sense. Didn't know about Luxon before..will check it out. 😃

**Comment by chrisdrackett** [comment]
<3 Luxon

**Comment by Aryk** [comment]
Yeah, I've been using it a lot in the last day. It's great, has simplified my code a ton. I hope it all ends up working with my backend Graphql...we'll see 😸
