### ISSUE TITLE
Automatically updating store upon query/mutation result

### ISSUE THREAD

**Issue by elie222** [mobxjs/mst-gql#5]
In the Twitter example I see this code:

```ts
    loadMessages(offset, count, replyTo = undefined) {
      const query = self.queryMessages(
        { offset, count, replyTo },
        MESSAGE_FRAGMENT
      )
      query.then(data => {
        self.sortedMessages.push(...data)
      })
      return query
    }
```

I assumed that the auto-generated `self.queryMessages` would update the MST store, but here I see it being done manually, so I take it this is not the case?

~~If not, why not? Seems like the codebase will be full of these manual updates to the store, whereas a library such as Apollo Client will update its store itself upon each query.~~

UPDATE: In the README I see the store does auto update after each query. So why does `loadMessages` in the example above manually add messages to the store?

**Comment by mweststrate** [comment]
The `sortedMessages` is the 'view' on the messages. The messages themselves are basically unordered, so sortedMessages makes sure that additionally fetched messages are appended to the end, while newly posted messages are prepended to the front. 

Note that this could also have been expressed as view, by sorting on the `timestamp` of the messages. (which would probably be a little bit cleaner)
