### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by mattiasewers** [mobxjs/mst-gql#6]

**Comment by mweststrate** [comment]
I don't see any reason why it wouldn't work with SSR at the moment.

**Comment by mattiasewers** [comment]
@mweststrate Sorry I should been more specific, how would I extract and restore data rendered on the server?

**Comment by mweststrate** [comment]
The standard MST primitives can be used for that:

const data = getSnapshot(store)

...

const store = RootStore.create(data, { client config and such })

**Comment by mattiasewers** [comment]
@mweststrate I'm having trouble getting ssr to work with next.js since we need resolve all the queries before rendering, like apollo does. How would you do it?

**Comment by mweststrate** [comment]
Create the store, invoke the relevant query methods, await them, then render

Op vr 31 mei 2019 12:23 schreef Mattias Ewers <notifications@github.com>:

**Comment by mattiasewers** [comment]
@mweststrate How do i know which queries to execute? Different pages might execute different queries

**Comment by mweststrate** [comment]
It will depend in whether you did put all the logic in components or on
stores. In the first case it would be hard to tell

Op vr 31 mei 2019 13:03 schreef Mattias Ewers <notifications@github.com>:

**Comment by mattiasewers** [comment]
@mweststrate I'm using `useQuery` hook to fetch data

**Comment by mweststrate** [comment]
are you invoking it like `useQuery(store => store.someQuery)` or are you
creating a query inside the component itself? If you use it from the store,
you can make sure the query happened already, and set the network policy to
cache-only to make sure the query resolves immediately

**Comment by mattiasewers** [comment]
@mweststrate ok, how?

**Comment by mweststrate** [comment]
In pseudo code it would be something like:

```javascript
aync handleDetailPageRender(id) {
   const store = RootStore.create(....)
   await store.queryPageDetail({ id })
   return renderToString(<StoreContext.Provider value={store}><MyPage id={id} /></StoreContext.Provider>)
}

const MyPage = ({ id }) => {
   data = useQuery(store => store.queryPageDetails({ id }, { fetchPolicy: "cache-only" })
   return renderThatData(data)
}
```

**Comment by mattiasewers** [comment]
@mweststrate ok that would work but it's not optimal. So I'm working with next.js and want resolve any query on a component before rendering without knowing the query. Apollo does this by traversering the react tree.

**Comment by mweststrate** [comment]
Ah, no, such a thing doesn't exist atm for mst-gql

**Comment by mattiasewers** [comment]
@mweststrate I'll look into it!

**Comment by mweststrate** [comment]
Awesome!

Op vr 31 mei 2019 15:20 schreef Mattias Ewers <notifications@github.com>:

**Comment by mattiasewers** [comment]
@mweststrate I've found a solution that worked for me. So the idea is that when you use `useQuery` we push the generated promise to some placeholder in the store e.i. 

```js
export const RootStore = RootStoreBase
  .props({
    __promises: types.optional(types.array(types.frozen()), [])
  })
  .actions(self => ({
    pushPromise(promise) {
      self.__promises.push(promise)
    }
  }))
```
and then in `normalizeQuery`, this is only need for ssr tho

```js
  const queryPromise = store.query(query, variables, {
    fetchPolicy: fetchPolicy,
    raw: raw
  });
  store.pushPromise(queryPromise.promise)
  return queryPromise
```
The only thing left to do on the server would be
```js
      
      const client = RootStore.create(undefined, {
        gqlHttpClient: createHttpClient('http://localhost:4000/graphql')
      });

      renderToStaticMarkup(
        <App client={client} />
      );

      await Promise.all(client.__promises)
```
This is kinda what apollo does, let me know what you think!

**Comment by mweststrate** [comment]
Sounds like a great idea to incorporate this!

Does this mean that the tree should be rendered twice on SSR? One to get
the promises, await them, render again? Doesn't sound too bad though :)

(small details: use .volatile instead of .props, and make sure to clean up
the collection, so Set would probably work better, but those are the
details)

**Comment by mattiasewers** [comment]
@mweststrate Yes, we unfortunately have to render twice on the server but it's the same trade of as apollo. This will also be solved once suspense is finished 😄 

I'll create a pr
