### ISSUE TITLE
optimistic updates with new items

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mst-gql#61]
I'm curious if anyone has thoughts around supporting optimistic updates when adding new items to the store. Because items are currently stored under their ID (which won't be available until a response comes back from the server) I'm not sure the best way to handle this case, if it is even possible.

**Comment by elie222** [comment]
So there are different cases, but I think each can be handled.

Create, update, delete.

When an update or delete happens you have the id in question. So you can
perform an optimistic update and then revert if the mutation fails.

Regarding create you can insert a new item inventing an id and then
removing the item once the real item is added from the server (or updating
the id, although I don’t remember if that is allowed).

For create and delete you would also have to update queries that rely on
this item.

**Comment by chrisdrackett** [comment]
yep, we're handling update and delete without any issue right now, but I'm just not sure how to handle the create case.

my current thought is this:

- create a temp ID when creating the item on the client
- send that ID to the server
- when the server sends back the real item, send back the temp ID as well.
- use the temp ID to replace the temp item on the client with the real item.

Ideally I'd love to get this working without getting the server involved, but I'm not sure how else to match the temp item with the item that ends up coming back from the server.

**Comment by elie222** [comment]
That process would work, but I'm not sure why the server needs the temp id
to match up.

If the client makes a request to the server, the client knows what the
request was made for.

The very rough code would look something like this:

```js
store.addItem({id: 'tempid', ...item})

const itemWithId = await createItemOnServer(item)

store.updateItem('tempid', itemWithId)
```
