### ISSUE TITLE
types on `data` returned from useQuery not correct

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mst-gql#66]
I think this is related to #47. it seems now that data is returned in the following format given something like `queryUser()` I now get:

```
data = {
   user: {
     email: 'test@test.com'
   }
}
```

however data is still typed as an instance of `User` so doing `data.user.email` gives me an error:

`Property 'user' does not exist on type 'ModelInstanceTypeProps…`

seems like we need to update the types for the `data` bit of the `useQuery` hook.

**Comment by chrisdrackett** [comment]
@mattiasewers, fyi!

**Comment by mattiasewers** [comment]
We should really write the tests in ts as well, anyway I'll take a look at it

**Comment by chrisdrackett** [comment]
looks like as part of this the examples need to be updated as well. I'm not currently able to get them to run, but adding as an FYI here.
