### ISSUE TITLE
move type to `<Name>Model.base.ts` from `<Name>Model.ts`?

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mst-gql#75]
Will the user ever have to edit or add to this line?

https://github.com/mobxjs/mst-gql/blob/7d15bf933d0b5fa76195c3547b2d405ad9b8a79f/examples/1-getting-started/src/app/models/TodoModel.ts#L6

If not, maybe it makes sense to move it to the generated file?

**Comment by mweststrate** [comment]
@chrisdrackett no, it never needs to change, although moving might theoretically complicate the resolve order and such (but I think it won't). Personally I think the biggest downside of moving is that then `TodoModelType` and `TodoModel` would be imported from different files.
