### ISSUE TITLE
mst-gql should support a `mst-gql.json` file for configuration

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mst-gql#8]
Instead, or additionally to, using the cli options, which can be pretty long. 

Also, some future options might need richer data than can be easily provided in a CLI.

**Comment by elie222** [comment]
Did you consider using graphql-codegen? It’s a library with type and code generators for lots of languages. Ts, flow, Apollo, urql... 

Cli/json options come out the box with it.

**Comment by elie222** [comment]
https://graphql-code-generator.com/docs/getting-started/

**Comment by mweststrate** [comment]
@elie222 yes, see #13
