### ISSUE TITLE
[Bug] when generate with --format js

### ISSUE THREAD

**Issue by williamtran29** [mobxjs/mst-gql#83]
when I ran the command:
$ yarn mst-gql --format js --force http://localhost:4000/graphql

it still generates like this in RootStore.base.js file, seem to be still typescript code with js format

```
export type PasswordMetaWhereInput = {
  id: string | undefined
  id_not: string | undefined
  id_in: string[]
  id_not_in: string[]
  id_lt: string | undefined
  id_lte: string | undefined
  id_gt: string | undefined
  id_gte: string | undefined
  id_contains: string | undefined
  id_not_contains: string | undefined
  id_starts_with: string | undefined
  id_not_starts_with: string | undefined
  id_ends_with: string | undefined
  id_not_ends_with: string | undefined
  resetToken: string | undefined
  resetToken_not: string | undefined
  resetToken_in: string[]
  resetToken_not_in: string[]
  resetToken_lt: string | undefined
  resetToken_lte: string | undefined
  resetToken_gt: string | undefined
  resetToken_gte: string | undefined
  resetToken_contains: string | undefined
  resetToken_not_contains: string | undefined
  resetToken_starts_with: string | undefined
  resetToken_not_starts_with: string | undefined
  resetToken_ends_with: string | undefined
  resetToken_not_ends_with: string | undefined
  AND: PasswordMetaWhereInput[]
  OR: PasswordMetaWhereInput[]
  NOT: PasswordMetaWhereInput[]
}
export type AwardFamilyWhereUniqueInput = {
  id: string | undefined
  name: string | undefined
  alias: string | undefined
}
```

**Comment by antondomratchev** [comment]
Do we want to define these types as MST models? I just encountered this issue on the new version

**Comment by mweststrate** [comment]
Please make sure to also include the original graphql definition from which this was generated. It might be that these were just generated for input types, for which we don't need a MST model, as they serve just to make the arguments to queries strongly typed.

**Comment by antondomratchev** [comment]
@mweststrate Thats the case for me, those types were generated from input types. I was wanting to try using these as MST models so I can generate forms directly from the models.

**Comment by mweststrate** [comment]
I see, sounds like something that could be done. Not fully sure that would
be in scope of this package though. (In the sense that the input object
really only reflect plain objects, without any capabilities, gql
integration, queries, methods etc etc. So the goal here seems to be just
reflection.
