### ISSUE TITLE
[Question] How to refetch a query after a mutation.

### ISSUE THREAD

**Issue by mukulhase** [mobxjs/mst-gql#87]
A component which uses "useQuery" doesn't get updated even if another component calls the same query after a mutation.

**Comment by chrisdrackett** [comment]
are you using `data` from the `useQuery` hook? If so, this is actually (in my understanding) currently looking at the cache of that query and not the store.

We get around this in our project by never using data and instead making sure we're always rendering from the store itself.

Notice here: https://github.com/mobxjs/mst-gql/blob/master/examples/3-twitter-clone/src/app/components/MessageWall.tsx#L18 how it is reading from the store and not the data from the query.

**Comment by mukulhase** [comment]
Yes I was using data. Thanks.
