### ISSUE TITLE
Should this project be used in production?

### ISSUE THREAD

**Issue by veeral-patel** [mobxjs/mst-gql#88]
Hi! Thanks for this project! I know this is experimental software, but is that because there's no maintainers or because it's not ready to be used in production? 

I haven't had any issues with it, so I feel comfortable integrating it into my app; let me know if this is a mistake.

**Comment by chrisdrackett** [comment]
I think mostly because its still a bit early and things like test coverage and typescript support are still a work in progress. That being said I'm also using this library in production (or close enough) without any worries or issue!

**Comment by veeral-patel** [comment]
Thank you! @chrisdrackett
